SELECT AVG(WS_EXT_DISCOUNT_AMT)
FROM TPCDS_BIN_PARTITIONED_ORC_5.WEB_SALES,
TPCDS_BIN_PARTITIONED_ORC_5.DATE_DIM
WHERE D_DATE BETWEEN ASYMMETRIC '2000-01-27' AND DATE_SUB(CAST('2000-01-27' AS DATE), CAST(72.34 AS int)) AND D_DATE_SK = WS_SOLD_DATE_SK
