SELECT PERCENTILE_APPROX(WS_EXT_DISCOUNT_AMT, 'cast(regexp_replace(''0.8d'', ''[^[:digit:]]''as int))')
FROM TPCDS_BIN_PARTITIONED_ORC_5.WEB_SALES,
TPCDS_BIN_PARTITIONED_ORC_5.DATE_DIM
WHERE D_DATE BETWEEN ASYMMETRIC '2000-01-27' AND DATE_ADD(CAST('2000-01-27' AS DATE), CAST(90.45 AS int))
FETCH NEXT 20 ROWS ONLY
