SELECT A.CA_STATE AS STATE, COUNT(*) AS CNT
FROM CUSTOMER_ADDRESS AS A,
CUSTOMER AS C,
STORE_SALES AS S,
DATE_DIM AS D,
ITEM AS I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK AND S.SS_SOLD_DATE_SK = D.D_DATE_SK AND S.SS_ITEM_SK = I.I_ITEM_SK AND D.D_MONTH_SEQ = (SELECT DISTINCT D_MONTH_SEQ
FROM DATE_DIM
WHERE D_YEAR = 2000 AND D_MOY = 1 AND D_DATE = DATE_ADD(CAST('2000-05-24' AS DATE), CAST('10.12' AS int))) AND I.I_CURRENT_PRICE > 1.2 * (SELECT AVG(J.I_CURRENT_PRICE)
FROM ITEM AS J
WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT
FETCH NEXT 100 ROWS ONLY
