SELECT CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, COUNT(*) AS CNT1, CD_PURCHASE_ESTIMATE, COUNT(*) AS CNT2, CD_CREDIT_RATING, COUNT(*) AS CNT3, CD_DEP_COUNT, COUNT(*) AS CNT4, CD_DEP_EMPLOYED_COUNT, COUNT(*) AS CNT5, CD_DEP_COLLEGE_COUNT, COUNT(*) AS CNT6
FROM CUSTOMER AS C,
CUSTOMER_ADDRESS AS CA,
CUSTOMER_DEMOGRAPHICS
WHERE C.C_CURRENT_ADDR_SK = CA.CA_ADDRESS_SK AND CA_COUNTY IN ('rush county', 'toole county', 'jefferson county', 'dona ana county', 'la porte county') AND CD_DEMO_SK = C.C_CURRENT_CDEMO_SK AND EXISTS (SELECT *
FROM STORE_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = SS_CUSTOMER_SK AND SS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3) AND (EXISTS (SELECT *
FROM WEB_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = WS_BILL_CUSTOMER_SK AND WS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3) OR EXISTS (SELECT *
FROM CATALOG_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = CS_SHIP_CUSTOMER_SK AND CS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3 AND D_DATE = DATE_SUB(CAST('2000-05-24' AS DATE), CAST('11.12' AS int))))
GROUP BY CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, CD_PURCHASE_ESTIMATE, CD_CREDIT_RATING, CD_DEP_COUNT, CD_DEP_EMPLOYED_COUNT, CD_DEP_COLLEGE_COUNT
ORDER BY CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, CD_PURCHASE_ESTIMATE, CD_CREDIT_RATING, CD_DEP_COUNT, CD_DEP_EMPLOYED_COUNT, CD_DEP_COLLEGE_COUNT
FETCH NEXT 100 ROWS ONLY
SELECT CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, COUNT(*) AS CNT1, CD_PURCHASE_ESTIMATE, COUNT(*) AS CNT2, CD_CREDIT_RATING, COUNT(*) AS CNT3, CD_DEP_COUNT, COUNT(*) AS CNT4, CD_DEP_EMPLOYED_COUNT, COUNT(*) AS CNT5, CD_DEP_COLLEGE_COUNT, COUNT(*) AS CNT6
FROM CUSTOMER AS C,
CUSTOMER_ADDRESS AS CA,
CUSTOMER_DEMOGRAPHICS
WHERE C.C_CURRENT_ADDR_SK = CA.CA_ADDRESS_SK AND CA_COUNTY IN ('rush county', 'toole county', 'jefferson county', 'dona ana county', 'la porte county') AND CD_DEMO_SK = C.C_CURRENT_CDEMO_SK AND EXISTS (SELECT *
FROM STORE_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = SS_CUSTOMER_SK AND SS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3) AND (EXISTS (SELECT *
FROM WEB_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = WS_BILL_CUSTOMER_SK AND WS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3) OR EXISTS (SELECT *
FROM CATALOG_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = CS_SHIP_CUSTOMER_SK AND CS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3 AND D_DATE = DATE_SUB(CAST('2000-05-24' AS DATE), CAST('11.12' AS int))))
GROUP BY CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, CD_PURCHASE_ESTIMATE, CD_CREDIT_RATING, CD_DEP_COUNT, CD_DEP_EMPLOYED_COUNT, CD_DEP_COLLEGE_COUNT
ORDER BY CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, CD_PURCHASE_ESTIMATE, CD_CREDIT_RATING, CD_DEP_COUNT, CD_DEP_EMPLOYED_COUNT, CD_DEP_COLLEGE_COUNT
FETCH NEXT 100 ROWS ONLY
SELECT CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, COUNT(*) AS CNT1, CD_PURCHASE_ESTIMATE, COUNT(*) AS CNT2, CD_CREDIT_RATING, COUNT(*) AS CNT3, CD_DEP_COUNT, COUNT(*) AS CNT4, CD_DEP_EMPLOYED_COUNT, COUNT(*) AS CNT5, CD_DEP_COLLEGE_COUNT, COUNT(*) AS CNT6
FROM CUSTOMER AS C,
CUSTOMER_ADDRESS AS CA,
CUSTOMER_DEMOGRAPHICS
WHERE C.C_CURRENT_ADDR_SK = CA.CA_ADDRESS_SK AND CA_COUNTY IN ('rush county', 'toole county', 'jefferson county', 'dona ana county', 'la porte county') AND CD_DEMO_SK = C.C_CURRENT_CDEMO_SK AND EXISTS (SELECT *
FROM STORE_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = SS_CUSTOMER_SK AND SS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3) AND (EXISTS (SELECT *
FROM WEB_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = WS_BILL_CUSTOMER_SK AND WS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3) OR EXISTS (SELECT *
FROM CATALOG_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = CS_SHIP_CUSTOMER_SK AND CS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3 AND D_DATE = DATE_SUB(CAST('2000-05-24' AS DATE), CAST('11.12' AS int))))
GROUP BY CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, CD_PURCHASE_ESTIMATE, CD_CREDIT_RATING, CD_DEP_COUNT, CD_DEP_EMPLOYED_COUNT, CD_DEP_COLLEGE_COUNT
ORDER BY CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, CD_PURCHASE_ESTIMATE, CD_CREDIT_RATING, CD_DEP_COUNT, CD_DEP_EMPLOYED_COUNT, CD_DEP_COLLEGE_COUNT
FETCH NEXT 100 ROWS ONLY
SELECT CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, COUNT(*) AS CNT1, CD_PURCHASE_ESTIMATE, COUNT(*) AS CNT2, CD_CREDIT_RATING, COUNT(*) AS CNT3, CD_DEP_COUNT, COUNT(*) AS CNT4, CD_DEP_EMPLOYED_COUNT, COUNT(*) AS CNT5, CD_DEP_COLLEGE_COUNT, COUNT(*) AS CNT6
FROM CUSTOMER AS C,
CUSTOMER_ADDRESS AS CA,
CUSTOMER_DEMOGRAPHICS
WHERE C.C_CURRENT_ADDR_SK = CA.CA_ADDRESS_SK AND CA_COUNTY IN ('rush county', 'toole county', 'jefferson county', 'dona ana county', 'la porte county') AND CD_DEMO_SK = C.C_CURRENT_CDEMO_SK AND EXISTS (SELECT *
FROM STORE_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = SS_CUSTOMER_SK AND SS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3) AND (EXISTS (SELECT *
FROM WEB_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = WS_BILL_CUSTOMER_SK AND WS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3) OR EXISTS (SELECT *
FROM CATALOG_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = CS_SHIP_CUSTOMER_SK AND CS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3 AND D_DATE = DATE_SUB(CAST('2000-05-24' AS DATE), CAST('11.12' AS int))))
GROUP BY CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, CD_PURCHASE_ESTIMATE, CD_CREDIT_RATING, CD_DEP_COUNT, CD_DEP_EMPLOYED_COUNT, CD_DEP_COLLEGE_COUNT
ORDER BY CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, CD_PURCHASE_ESTIMATE, CD_CREDIT_RATING, CD_DEP_COUNT, CD_DEP_EMPLOYED_COUNT, CD_DEP_COLLEGE_COUNT
FETCH NEXT 100 ROWS ONLY
SELECT CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, COUNT(*) AS CNT1, CD_PURCHASE_ESTIMATE, COUNT(*) AS CNT2, CD_CREDIT_RATING, COUNT(*) AS CNT3, CD_DEP_COUNT, COUNT(*) AS CNT4, CD_DEP_EMPLOYED_COUNT, COUNT(*) AS CNT5, CD_DEP_COLLEGE_COUNT, COUNT(*) AS CNT6
FROM CUSTOMER AS C,
CUSTOMER_ADDRESS AS CA,
CUSTOMER_DEMOGRAPHICS
WHERE C.C_CURRENT_ADDR_SK = CA.CA_ADDRESS_SK AND CA_COUNTY IN ('rush county', 'toole county', 'jefferson county', 'dona ana county', 'la porte county') AND CD_DEMO_SK = C.C_CURRENT_CDEMO_SK AND EXISTS (SELECT *
FROM STORE_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = SS_CUSTOMER_SK AND SS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3) AND (EXISTS (SELECT *
FROM WEB_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = WS_BILL_CUSTOMER_SK AND WS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3) OR EXISTS (SELECT *
FROM CATALOG_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = CS_SHIP_CUSTOMER_SK AND CS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3 AND D_DATE = DATE_SUB(CAST('2000-05-24' AS DATE), CAST('11.12' AS int))))
GROUP BY CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, CD_PURCHASE_ESTIMATE, CD_CREDIT_RATING, CD_DEP_COUNT, CD_DEP_EMPLOYED_COUNT, CD_DEP_COLLEGE_COUNT
ORDER BY CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, CD_PURCHASE_ESTIMATE, CD_CREDIT_RATING, CD_DEP_COUNT, CD_DEP_EMPLOYED_COUNT, CD_DEP_COLLEGE_COUNT
FETCH NEXT 100 ROWS ONLY
SELECT CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, COUNT(*) AS CNT1, CD_PURCHASE_ESTIMATE, COUNT(*) AS CNT2, CD_CREDIT_RATING, COUNT(*) AS CNT3, CD_DEP_COUNT, COUNT(*) AS CNT4, CD_DEP_EMPLOYED_COUNT, COUNT(*) AS CNT5, CD_DEP_COLLEGE_COUNT, COUNT(*) AS CNT6
FROM CUSTOMER AS C,
CUSTOMER_ADDRESS AS CA,
CUSTOMER_DEMOGRAPHICS
WHERE C.C_CURRENT_ADDR_SK = CA.CA_ADDRESS_SK AND CA_COUNTY IN ('rush county', 'toole county', 'jefferson county', 'dona ana county', 'la porte county') AND CD_DEMO_SK = C.C_CURRENT_CDEMO_SK AND EXISTS (SELECT *
FROM STORE_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = SS_CUSTOMER_SK AND SS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3) AND (EXISTS (SELECT *
FROM WEB_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = WS_BILL_CUSTOMER_SK AND WS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3) OR EXISTS (SELECT *
FROM CATALOG_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = CS_SHIP_CUSTOMER_SK AND CS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3 AND D_DATE = DATE_SUB(CAST('2000-05-24' AS DATE), CAST('11.12' AS int))))
GROUP BY CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, CD_PURCHASE_ESTIMATE, CD_CREDIT_RATING, CD_DEP_COUNT, CD_DEP_EMPLOYED_COUNT, CD_DEP_COLLEGE_COUNT
ORDER BY CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, CD_PURCHASE_ESTIMATE, CD_CREDIT_RATING, CD_DEP_COUNT, CD_DEP_EMPLOYED_COUNT, CD_DEP_COLLEGE_COUNT
FETCH NEXT 100 ROWS ONLY
SELECT CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, COUNT(*) AS CNT1, CD_PURCHASE_ESTIMATE, COUNT(*) AS CNT2, CD_CREDIT_RATING, COUNT(*) AS CNT3, CD_DEP_COUNT, COUNT(*) AS CNT4, CD_DEP_EMPLOYED_COUNT, COUNT(*) AS CNT5, CD_DEP_COLLEGE_COUNT, COUNT(*) AS CNT6
FROM CUSTOMER AS C,
CUSTOMER_ADDRESS AS CA,
CUSTOMER_DEMOGRAPHICS
WHERE C.C_CURRENT_ADDR_SK = CA.CA_ADDRESS_SK AND CA_COUNTY IN ('rush county', 'toole county', 'jefferson county', 'dona ana county', 'la porte county') AND CD_DEMO_SK = C.C_CURRENT_CDEMO_SK AND EXISTS (SELECT *
FROM STORE_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = SS_CUSTOMER_SK AND SS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3) AND (EXISTS (SELECT *
FROM WEB_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = WS_BILL_CUSTOMER_SK AND WS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3) OR EXISTS (SELECT *
FROM CATALOG_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = CS_SHIP_CUSTOMER_SK AND CS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3 AND D_DATE = DATE_SUB(CAST('2000-05-24' AS DATE), CAST('11.12' AS int))))
GROUP BY CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, CD_PURCHASE_ESTIMATE, CD_CREDIT_RATING, CD_DEP_COUNT, CD_DEP_EMPLOYED_COUNT, CD_DEP_COLLEGE_COUNT
ORDER BY CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, CD_PURCHASE_ESTIMATE, CD_CREDIT_RATING, CD_DEP_COUNT, CD_DEP_EMPLOYED_COUNT, CD_DEP_COLLEGE_COUNT
FETCH NEXT 100 ROWS ONLY
SELECT CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, COUNT(*) AS CNT1, CD_PURCHASE_ESTIMATE, COUNT(*) AS CNT2, CD_CREDIT_RATING, COUNT(*) AS CNT3, CD_DEP_COUNT, COUNT(*) AS CNT4, CD_DEP_EMPLOYED_COUNT, COUNT(*) AS CNT5, CD_DEP_COLLEGE_COUNT, COUNT(*) AS CNT6
FROM CUSTOMER AS C,
CUSTOMER_ADDRESS AS CA,
CUSTOMER_DEMOGRAPHICS
WHERE C.C_CURRENT_ADDR_SK = CA.CA_ADDRESS_SK AND CA_COUNTY IN ('rush county', 'toole county', 'jefferson county', 'dona ana county', 'la porte county') AND CD_DEMO_SK = C.C_CURRENT_CDEMO_SK AND EXISTS (SELECT *
FROM STORE_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = SS_CUSTOMER_SK AND SS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3) AND (EXISTS (SELECT *
FROM WEB_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = WS_BILL_CUSTOMER_SK AND WS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3) OR EXISTS (SELECT *
FROM CATALOG_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = CS_SHIP_CUSTOMER_SK AND CS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3 AND D_DATE = DATE_SUB(CAST('2000-05-24' AS DATE), CAST('11.12' AS int))))
GROUP BY CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, CD_PURCHASE_ESTIMATE, CD_CREDIT_RATING, CD_DEP_COUNT, CD_DEP_EMPLOYED_COUNT, CD_DEP_COLLEGE_COUNT
ORDER BY CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, CD_PURCHASE_ESTIMATE, CD_CREDIT_RATING, CD_DEP_COUNT, CD_DEP_EMPLOYED_COUNT, CD_DEP_COLLEGE_COUNT
FETCH NEXT 100 ROWS ONLY
SELECT CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, COUNT(*) AS CNT1, CD_PURCHASE_ESTIMATE, COUNT(*) AS CNT2, CD_CREDIT_RATING, COUNT(*) AS CNT3, CD_DEP_COUNT, COUNT(*) AS CNT4, CD_DEP_EMPLOYED_COUNT, COUNT(*) AS CNT5, CD_DEP_COLLEGE_COUNT, COUNT(*) AS CNT6
FROM CUSTOMER AS C,
CUSTOMER_ADDRESS AS CA,
CUSTOMER_DEMOGRAPHICS
WHERE C.C_CURRENT_ADDR_SK = CA.CA_ADDRESS_SK AND CA_COUNTY IN ('rush county', 'toole county', 'jefferson county', 'dona ana county', 'la porte county') AND CD_DEMO_SK = C.C_CURRENT_CDEMO_SK AND EXISTS (SELECT *
FROM STORE_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = SS_CUSTOMER_SK AND SS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3) AND (EXISTS (SELECT *
FROM WEB_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = WS_BILL_CUSTOMER_SK AND WS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3) OR EXISTS (SELECT *
FROM CATALOG_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = CS_SHIP_CUSTOMER_SK AND CS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3 AND D_DATE = DATE_SUB(CAST('2000-05-24' AS DATE), CAST('11.12' AS int))))
GROUP BY CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, CD_PURCHASE_ESTIMATE, CD_CREDIT_RATING, CD_DEP_COUNT, CD_DEP_EMPLOYED_COUNT, CD_DEP_COLLEGE_COUNT
ORDER BY CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, CD_PURCHASE_ESTIMATE, CD_CREDIT_RATING, CD_DEP_COUNT, CD_DEP_EMPLOYED_COUNT, CD_DEP_COLLEGE_COUNT
FETCH NEXT 100 ROWS ONLY
SELECT CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, COUNT(*) AS CNT1, CD_PURCHASE_ESTIMATE, COUNT(*) AS CNT2, CD_CREDIT_RATING, COUNT(*) AS CNT3, CD_DEP_COUNT, COUNT(*) AS CNT4, CD_DEP_EMPLOYED_COUNT, COUNT(*) AS CNT5, CD_DEP_COLLEGE_COUNT, COUNT(*) AS CNT6
FROM CUSTOMER AS C,
CUSTOMER_ADDRESS AS CA,
CUSTOMER_DEMOGRAPHICS
WHERE C.C_CURRENT_ADDR_SK = CA.CA_ADDRESS_SK AND CA_COUNTY IN ('rush county', 'toole county', 'jefferson county', 'dona ana county', 'la porte county') AND CD_DEMO_SK = C.C_CURRENT_CDEMO_SK AND EXISTS (SELECT *
FROM STORE_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = SS_CUSTOMER_SK AND SS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3) AND (EXISTS (SELECT *
FROM WEB_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = WS_BILL_CUSTOMER_SK AND WS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3) OR EXISTS (SELECT *
FROM CATALOG_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = CS_SHIP_CUSTOMER_SK AND CS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3 AND D_DATE = DATE_SUB(CAST('2000-05-24' AS DATE), CAST('11.12' AS int))))
GROUP BY CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, CD_PURCHASE_ESTIMATE, CD_CREDIT_RATING, CD_DEP_COUNT, CD_DEP_EMPLOYED_COUNT, CD_DEP_COLLEGE_COUNT
ORDER BY CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, CD_PURCHASE_ESTIMATE, CD_CREDIT_RATING, CD_DEP_COUNT, CD_DEP_EMPLOYED_COUNT, CD_DEP_COLLEGE_COUNT
FETCH NEXT 100 ROWS ONLY
SELECT CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, COUNT(*) AS CNT1, CD_PURCHASE_ESTIMATE, COUNT(*) AS CNT2, CD_CREDIT_RATING, COUNT(*) AS CNT3, CD_DEP_COUNT, COUNT(*) AS CNT4, CD_DEP_EMPLOYED_COUNT, COUNT(*) AS CNT5, CD_DEP_COLLEGE_COUNT, COUNT(*) AS CNT6
FROM CUSTOMER AS C,
CUSTOMER_ADDRESS AS CA,
CUSTOMER_DEMOGRAPHICS
WHERE C.C_CURRENT_ADDR_SK = CA.CA_ADDRESS_SK AND CA_COUNTY IN ('rush county', 'toole county', 'jefferson county', 'dona ana county', 'la porte county') AND CD_DEMO_SK = C.C_CURRENT_CDEMO_SK AND EXISTS (SELECT *
FROM STORE_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = SS_CUSTOMER_SK AND SS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3) AND (EXISTS (SELECT *
FROM WEB_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = WS_BILL_CUSTOMER_SK AND WS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3) OR EXISTS (SELECT *
FROM CATALOG_SALES,
DATE_DIM
WHERE C.C_CUSTOMER_SK = CS_SHIP_CUSTOMER_SK AND CS_SOLD_DATE_SK = D_DATE_SK AND D_YEAR = 2002 AND D_MOY BETWEEN ASYMMETRIC 1 AND 1 + 3 AND D_DATE = DATE_SUB(CAST('2000-05-24' AS DATE), CAST('11.12' AS int))))
GROUP BY CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, CD_PURCHASE_ESTIMATE, CD_CREDIT_RATING, CD_DEP_COUNT, CD_DEP_EMPLOYED_COUNT, CD_DEP_COLLEGE_COUNT
ORDER BY CD_GENDER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS, CD_PURCHASE_ESTIMATE, CD_CREDIT_RATING, CD_DEP_COUNT, CD_DEP_EMPLOYED_COUNT, CD_DEP_COLLEGE_COUNT
FETCH NEXT 100 ROWS ONLY
