SELECT SUM(WS_EXT_DISCOUNT_AMT) AS excess discount amount
FROM TPCDS_BIN_PARTITIONED_ORC_5.WEB_SALES,
TPCDS_BIN_PARTITIONED_ORC_5.ITEM,
TPCDS_BIN_PARTITIONED_ORC_5.DATE_DIM
WHERE I_MANUFACT_ID = 350 AND I_ITEM_SK = WS_ITEM_SK AND D_DATE BETWEEN ASYMMETRIC '2000-01-27' AND DATE_ADD(CAST('2000-01-27' AS DATE), CAST(90.86 AS int)) AND D_DATE_SK = WS_SOLD_DATE_SK
