SELECT SUBSTR(W_WAREHOUSE_NAME, 1, 20), SM_TYPE, CC_NAME, SUM(CASE WHEN CS_SHIP_DATE_SK - CS_SOLD_DATE_SK <= 30 THEN 1 ELSE 0 END) AS 30 day, SUM(CASE WHEN CS_SHIP_DATE_SK - CS_SOLD_DATE_SK > 30 AND CS_SHIP_DATE_SK - CS_SOLD_DATE_SK <= 60 THEN 1 ELSE 0 END) AS 31-60 day, SUM(CASE WHEN CS_SHIP_DATE_SK - CS_SOLD_DATE_SK > 60 AND CS_SHIP_DATE_SK - CS_SOLD_DATE_SK <= 90 THEN 1 ELSE 0 END) AS 61-90 day, SUM(CASE WHEN CS_SHIP_DATE_SK - CS_SOLD_DATE_SK > 90 AND CS_SHIP_DATE_SK - CS_SOLD_DATE_SK <= 120 THEN 1 ELSE 0 END) AS 91-120 day, SUM(CASE WHEN CS_SHIP_DATE_SK - CS_SOLD_DATE_SK > 120 THEN 1 ELSE 0 END) AS >120 day
FROM CATALOG_SALES,
WAREHOUSE,
SHIP_MODE,
CALL_CENTER,
DATE_DIM
WHERE D_MONTH_SEQ BETWEEN  1212 AND 1212 + 11 AND CS_SHIP_DATE_SK = D_DATE_SK AND CS_WAREHOUSE_SK = W_WAREHOUSE_SK AND CS_SHIP_MODE_SK = SM_SHIP_MODE_SK AND CS_CALL_CENTER_SK = CC_CALL_CENTER_SK
GROUP BY SUBSTR(W_WAREHOUSE_NAME, 1, 20), SM_TYPE, CC_NAME
ORDER BY SUBSTR(W_WAREHOUSE_NAME, 1, 20), SM_TYPE, CC_NAME
FETCH NEXT 100 ROWS ONLY
