SELECT MAX_DAY.THUMB_IMAGE, MAX_DAY.TITLE, MAX_DAY.TREND, MAX_DAY.WAIST_LENGTH, MAX_DAY.DELTA_HASH
FROM (SELECT *
FROM DIGITALDATA_DB.PRODUCTREACH
WHERE RUN_TIME IN (SELECT RUN_TIME
FROM DIGITALDATA_DB.PRODUCTREACH
WHERE RUN_TIME >= CAST(UNIX_SECONDS(DATE_ADD(CURRENT_DATE, -1)) AS STRING)
ORDER BY RUN_TIME DESC
FETCH NEXT 1 ROWS ONLY)) AS MAX_DAY
LEFT JOIN (SELECT *
FROM DIGITALDATA_DB.PRODUCTREACH
WHERE RUN_TIME IN (SELECT RUN_TIME
FROM (SELECT DISTINCT RUN_TIME
FROM DIGITALDATA_DB.PRODUCTREACH
WHERE RUN_TIME >= CAST(UNIX_SECONDS(DATE_ADD(CURRENT_DATE, -1)) AS STRING)
ORDER BY RUN_TIME DESC
FETCH NEXT 2 ROWS ONLY) AS D
ORDER BY RUN_TIME
FETCH NEXT 1 ROWS ONLY)) AS SECOND_MAX_DAY ON MAX_DAY.SKUID = SECOND_MAX_DAY.SKUID AND MAX_DAY.PID = SECOND_MAX_DAY.PID AND MAX_DAY.DELTA_HASH = SECOND_MAX_DAY.DELTA_HASH
