---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_dc_to_dc -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2923 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ----------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_dc_to_dc_intra -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-3287 ssoma dc to dc intra initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ----------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_dc_to_store -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2922 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.03 04may20 scctp4-3331 ssoma hql optimization  -- 01.00.00.04 17jan21 scctp-601 kaali m replaced handling_master table with handling_master_poso  ----------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_dc_to_store_intra -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-3287 ssoma dc to store intra initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.03 04may20 scctp4-3331 ssoma hql optimization  -- 01.00.00.04 17jan21 scctp-601 kaali m replaced handling_master table with handling_master_poso  ----------------------------------------------------------------------------   ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_gpom -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2276 ssoma initial version -- 01.00.00.02 09oct19 scctp4-2523 ssoma changed partition columns and added new column -- 01.00.00.03 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.04 04may20 scctp4-3331 ssoma hql optimization  ----------------------------------------------------------------------------  -------------------------  ------------------------- ---loading po line kpis data into po_so_dd_hu_details table for gpom model -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_mbp_nb -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2276 ssoma initial version -- 01.00.00.02 16oct19 scctp4-2523 ssoma changed partition columns and po for so model -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.04 05nov20 scctp-456 fyuan add fg filter ---------------------------------------------------------------------------  ------------------------- ---loading po line kpis data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details for mast beauty production;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_mbp_vsd_gs -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master,location_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2931 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ---------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_tkvsd -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, inventory_movement ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 27dec19 scctp4-3287 ssoma turnkey production to vsd initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ---------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_ven_rfc -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master,location_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2931 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ---------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_vendor_to_dc -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, inventory_movement ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 27dec19 scctp4-2996 ssoma component inflow initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ---------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_vsdinflow -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 06jan20 scctp4-3287 ssoma vsd inflow initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ----------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_vss_vsd -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 06jan20 scctp4-2924 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.03 04may20 scctp4-3331 ssoma hql optimization  ----------------------------------------------------------------------------   ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_vtptobdc_nb -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, inventory_movement ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 27dec19 scctp4-2901 ssoma turnkey production to brand initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ---------------------------------------------------------------------------  ------------------------- ---loading po line kpis data into po_so_dd_hu_details table for vendor turnkey production -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_zdtd -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug20 scctp5-327 fyuan zdtd initial version ---------------------------------------------------------------------------- ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_kpi_details_po -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_kpi_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2276 ssoma initial version -- 01.00.00.02 09oct19 scctp4-2523 ssoma changed partition columns and added new column -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.04 05nov20 scctp-456 fyuan add component filter  --------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_kpi_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_kpi_details;
! echo completed po_so_dd_hu_kpi_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_kpi_details_podd -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_kpi_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2276 ssoma initial version -- 01.00.00.02 09oct19 scctp4-2523 ssoma changed partition columns and added new column -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.03 20aug20 scctp5-327 fyuan add zdtd  --------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_kpi_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_kpi_details;
! echo completed po_so_dd_hu_kpi_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_kpi_details_posodd -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_kpi_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2276 ssoma initial version -- 01.00.00.02 09oct19 scctp4-2523 ssoma changed partition columns and added new column -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter --------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_kpi_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_kpi_details;
! echo completed po_so_dd_hu_kpi_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_kpi_details_sodd -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_kpi_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2276 ssoma initial version -- 01.00.00.02 09oct19 scctp4-2523 ssoma changed partition columns and added new column -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter --------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_kpi_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_kpi_details;
! echo completed po_so_dd_hu_kpi_details data load;
---jobname:scct-e2e_dashboard-hive-stg1-scct_db.prepack_component -------------------------------------------------------------------------- ---target: stage1 table: scct_db.prepack_component  ---source: scct_db table : bom_item, bom_detail, analytics_view table : item ---load type: full ---back posting: no ---author: ryadav ---last modified date: 12/18/2018 --------------------------------------------------------------------------  ------------------------- ---loading prepack_component stage 1 base data -------------------------  ! echo started loading into scct_db.prepack_component ;
INSERT OVERWRITE INTO SCCT_DB.PREPACK_COMPONENT
(SELECT COALESCE(CASE WHEN TRIM( A.BOM_ITEM_NBR) = '' THEN NULL ELSE TRIM( A.BOM_ITEM_NBR) END, 'n/a') AS PPCK_ITM_NBR, COALESCE(CASE WHEN TRIM( B.BOM_CPNT_ITEM_NBR) = '' THEN NULL ELSE TRIM( B.BOM_CPNT_ITEM_NBR) END, 'n/a') AS PPCK_CPNT_ITM_NBR, COALESCE(CASE WHEN B.BOM_CPNT_QTY = '' THEN NULL ELSE B.BOM_CPNT_QTY END, 0.00) AS PPCK_CPNT_ITEM_QTY, COALESCE(CASE WHEN TRIM( B.BOM_CPNT_UNT_OF_MEAS_CD) = '' THEN NULL ELSE TRIM( B.BOM_CPNT_UNT_OF_MEAS_CD) END, 'n/a') AS PPCK_CPNT_UNT_OF_MEAS
FROM SCCT_DB.BOM_ITEM AS A
INNER JOIN SCCT_DB.BOM_DETAIL AS B ON A.BOM_NBR = B.BOM_NBR
INNER JOIN ANALYTICS_VIEW.ITEM AS C ON A.BOM_ITEM_NBR = C.ITEM_NUMBER
WHERE C.ITEM_TYPE_CODE = 'zpre'
GROUP BY A.BOM_ITEM_NBR, B.BOM_CPNT_ITEM_NBR, B.BOM_CPNT_QTY, B.BOM_CPNT_UNT_OF_MEAS_CD);
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_dc_to_dc -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2923 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ----------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_dc_to_dc_intra -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-3287 ssoma dc to dc intra initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ----------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_dc_to_store -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2922 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.03 04may20 scctp4-3331 ssoma hql optimization  -- 01.00.00.04 17jan21 scctp-601 kaali m replaced handling_master table with handling_master_poso  ----------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_dc_to_store_intra -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-3287 ssoma dc to store intra initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.03 04may20 scctp4-3331 ssoma hql optimization  -- 01.00.00.04 17jan21 scctp-601 kaali m replaced handling_master table with handling_master_poso  ----------------------------------------------------------------------------   ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_gpom -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2276 ssoma initial version -- 01.00.00.02 09oct19 scctp4-2523 ssoma changed partition columns and added new column -- 01.00.00.03 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.04 04may20 scctp4-3331 ssoma hql optimization  ----------------------------------------------------------------------------  -------------------------  ------------------------- ---loading po line kpis data into po_so_dd_hu_details table for gpom model -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_mbp_nb -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2276 ssoma initial version -- 01.00.00.02 16oct19 scctp4-2523 ssoma changed partition columns and po for so model -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.04 05nov20 scctp-456 fyuan add fg filter ---------------------------------------------------------------------------  ------------------------- ---loading po line kpis data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details for mast beauty production;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_mbp_vsd_gs -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master,location_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2931 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ---------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_tkvsd -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, inventory_movement ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 27dec19 scctp4-3287 ssoma turnkey production to vsd initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ---------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_ven_rfc -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master,location_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2931 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ---------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_vendor_to_dc -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, inventory_movement ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 27dec19 scctp4-2996 ssoma component inflow initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ---------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_vsdinflow -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 06jan20 scctp4-3287 ssoma vsd inflow initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ----------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_vss_vsd -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 06jan20 scctp4-2924 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.03 04may20 scctp4-3331 ssoma hql optimization  ----------------------------------------------------------------------------   ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_vtptobdc_nb -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, inventory_movement ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 27dec19 scctp4-2901 ssoma turnkey production to brand initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ---------------------------------------------------------------------------  ------------------------- ---loading po line kpis data into po_so_dd_hu_details table for vendor turnkey production -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_zdtd -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug20 scctp5-327 fyuan zdtd initial version ---------------------------------------------------------------------------- ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_kpi_details_po -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_kpi_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2276 ssoma initial version -- 01.00.00.02 09oct19 scctp4-2523 ssoma changed partition columns and added new column -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.04 05nov20 scctp-456 fyuan add component filter  --------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_kpi_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_kpi_details;
! echo completed po_so_dd_hu_kpi_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_kpi_details_podd -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_kpi_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2276 ssoma initial version -- 01.00.00.02 09oct19 scctp4-2523 ssoma changed partition columns and added new column -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.03 20aug20 scctp5-327 fyuan add zdtd  --------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_kpi_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_kpi_details;
! echo completed po_so_dd_hu_kpi_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_kpi_details_posodd -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_kpi_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2276 ssoma initial version -- 01.00.00.02 09oct19 scctp4-2523 ssoma changed partition columns and added new column -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter --------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_kpi_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_kpi_details;
! echo completed po_so_dd_hu_kpi_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_kpi_details_sodd -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_kpi_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2276 ssoma initial version -- 01.00.00.02 09oct19 scctp4-2523 ssoma changed partition columns and added new column -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter --------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_kpi_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_kpi_details;
! echo completed po_so_dd_hu_kpi_details data load;
---jobname:scct-e2e_dashboard-hive-stg1-scct_db.prepack_component -------------------------------------------------------------------------- ---target: stage1 table: scct_db.prepack_component  ---source: scct_db table : bom_item, bom_detail, analytics_view table : item ---load type: full ---back posting: no ---author: ryadav ---last modified date: 12/18/2018 --------------------------------------------------------------------------  ------------------------- ---loading prepack_component stage 1 base data -------------------------  ! echo started loading into scct_db.prepack_component ;
INSERT OVERWRITE INTO SCCT_DB.PREPACK_COMPONENT
(SELECT COALESCE(CASE WHEN TRIM( A.BOM_ITEM_NBR) = '' THEN NULL ELSE TRIM( A.BOM_ITEM_NBR) END, 'n/a') AS PPCK_ITM_NBR, COALESCE(CASE WHEN TRIM( B.BOM_CPNT_ITEM_NBR) = '' THEN NULL ELSE TRIM( B.BOM_CPNT_ITEM_NBR) END, 'n/a') AS PPCK_CPNT_ITM_NBR, COALESCE(CASE WHEN B.BOM_CPNT_QTY = '' THEN NULL ELSE B.BOM_CPNT_QTY END, 0.00) AS PPCK_CPNT_ITEM_QTY, COALESCE(CASE WHEN TRIM( B.BOM_CPNT_UNT_OF_MEAS_CD) = '' THEN NULL ELSE TRIM( B.BOM_CPNT_UNT_OF_MEAS_CD) END, 'n/a') AS PPCK_CPNT_UNT_OF_MEAS
FROM SCCT_DB.BOM_ITEM AS A
INNER JOIN SCCT_DB.BOM_DETAIL AS B ON A.BOM_NBR = B.BOM_NBR
INNER JOIN ANALYTICS_VIEW.ITEM AS C ON A.BOM_ITEM_NBR = C.ITEM_NUMBER
WHERE C.ITEM_TYPE_CODE = 'zpre'
GROUP BY A.BOM_ITEM_NBR, B.BOM_CPNT_ITEM_NBR, B.BOM_CPNT_QTY, B.BOM_CPNT_UNT_OF_MEAS_CD);
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_dc_to_dc -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2923 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ----------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_dc_to_dc_intra -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-3287 ssoma dc to dc intra initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ----------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_dc_to_store -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2922 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.03 04may20 scctp4-3331 ssoma hql optimization  -- 01.00.00.04 17jan21 scctp-601 kaali m replaced handling_master table with handling_master_poso  ----------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_dc_to_store_intra -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-3287 ssoma dc to store intra initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.03 04may20 scctp4-3331 ssoma hql optimization  -- 01.00.00.04 17jan21 scctp-601 kaali m replaced handling_master table with handling_master_poso  ----------------------------------------------------------------------------   ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_gpom -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2276 ssoma initial version -- 01.00.00.02 09oct19 scctp4-2523 ssoma changed partition columns and added new column -- 01.00.00.03 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.04 04may20 scctp4-3331 ssoma hql optimization  ----------------------------------------------------------------------------  -------------------------  ------------------------- ---loading po line kpis data into po_so_dd_hu_details table for gpom model -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_mbp_nb -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2276 ssoma initial version -- 01.00.00.02 16oct19 scctp4-2523 ssoma changed partition columns and po for so model -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.04 05nov20 scctp-456 fyuan add fg filter ---------------------------------------------------------------------------  ------------------------- ---loading po line kpis data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details for mast beauty production;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_mbp_vsd_gs -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master,location_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2931 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ---------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_tkvsd -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, inventory_movement ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 27dec19 scctp4-3287 ssoma turnkey production to vsd initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ---------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_ven_rfc -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master,location_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2931 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ---------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_vendor_to_dc -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, inventory_movement ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 27dec19 scctp4-2996 ssoma component inflow initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ---------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_vsdinflow -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 06jan20 scctp4-3287 ssoma vsd inflow initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ----------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_vss_vsd -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 06jan20 scctp4-2924 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.03 04may20 scctp4-3331 ssoma hql optimization  ----------------------------------------------------------------------------   ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_vtptobdc_nb -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, inventory_movement ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 27dec19 scctp4-2901 ssoma turnkey production to brand initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ---------------------------------------------------------------------------  ------------------------- ---loading po line kpis data into po_so_dd_hu_details table for vendor turnkey production -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_zdtd -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug20 scctp5-327 fyuan zdtd initial version ---------------------------------------------------------------------------- ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_kpi_details_po -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_kpi_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2276 ssoma initial version -- 01.00.00.02 09oct19 scctp4-2523 ssoma changed partition columns and added new column -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.04 05nov20 scctp-456 fyuan add component filter  --------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_kpi_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_kpi_details;
! echo completed po_so_dd_hu_kpi_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_kpi_details_podd -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_kpi_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2276 ssoma initial version -- 01.00.00.02 09oct19 scctp4-2523 ssoma changed partition columns and added new column -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.03 20aug20 scctp5-327 fyuan add zdtd  --------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_kpi_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_kpi_details;
! echo completed po_so_dd_hu_kpi_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_kpi_details_posodd -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_kpi_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2276 ssoma initial version -- 01.00.00.02 09oct19 scctp4-2523 ssoma changed partition columns and added new column -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter --------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_kpi_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_kpi_details;
! echo completed po_so_dd_hu_kpi_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_kpi_details_sodd -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_kpi_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2276 ssoma initial version -- 01.00.00.02 09oct19 scctp4-2523 ssoma changed partition columns and added new column -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter --------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_kpi_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_kpi_details;
! echo completed po_so_dd_hu_kpi_details data load;
---jobname:scct-e2e_dashboard-hive-stg1-scct_db.prepack_component -------------------------------------------------------------------------- ---target: stage1 table: scct_db.prepack_component  ---source: scct_db table : bom_item, bom_detail, analytics_view table : item ---load type: full ---back posting: no ---author: ryadav ---last modified date: 12/18/2018 --------------------------------------------------------------------------  ------------------------- ---loading prepack_component stage 1 base data -------------------------  ! echo started loading into scct_db.prepack_component ;
INSERT OVERWRITE INTO SCCT_DB.PREPACK_COMPONENT
(SELECT COALESCE(CASE WHEN TRIM( A.BOM_ITEM_NBR) = '' THEN NULL ELSE TRIM( A.BOM_ITEM_NBR) END, 'n/a') AS PPCK_ITM_NBR, COALESCE(CASE WHEN TRIM( B.BOM_CPNT_ITEM_NBR) = '' THEN NULL ELSE TRIM( B.BOM_CPNT_ITEM_NBR) END, 'n/a') AS PPCK_CPNT_ITM_NBR, COALESCE(CASE WHEN B.BOM_CPNT_QTY = '' THEN NULL ELSE B.BOM_CPNT_QTY END, 0.00) AS PPCK_CPNT_ITEM_QTY, COALESCE(CASE WHEN TRIM( B.BOM_CPNT_UNT_OF_MEAS_CD) = '' THEN NULL ELSE TRIM( B.BOM_CPNT_UNT_OF_MEAS_CD) END, 'n/a') AS PPCK_CPNT_UNT_OF_MEAS
FROM SCCT_DB.BOM_ITEM AS A
INNER JOIN SCCT_DB.BOM_DETAIL AS B ON A.BOM_NBR = B.BOM_NBR
INNER JOIN ANALYTICS_VIEW.ITEM AS C ON A.BOM_ITEM_NBR = C.ITEM_NUMBER
WHERE C.ITEM_TYPE_CODE = 'zpre'
GROUP BY A.BOM_ITEM_NBR, B.BOM_CPNT_ITEM_NBR, B.BOM_CPNT_QTY, B.BOM_CPNT_UNT_OF_MEAS_CD);
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_dc_to_dc -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2923 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ----------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_dc_to_dc_intra -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-3287 ssoma dc to dc intra initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ----------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_dc_to_store -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2922 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.03 04may20 scctp4-3331 ssoma hql optimization  -- 01.00.00.04 17jan21 scctp-601 kaali m replaced handling_master table with handling_master_poso  ----------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_dc_to_store_intra -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-3287 ssoma dc to store intra initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.03 04may20 scctp4-3331 ssoma hql optimization  -- 01.00.00.04 17jan21 scctp-601 kaali m replaced handling_master table with handling_master_poso  ----------------------------------------------------------------------------   ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_gpom -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2276 ssoma initial version -- 01.00.00.02 09oct19 scctp4-2523 ssoma changed partition columns and added new column -- 01.00.00.03 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.04 04may20 scctp4-3331 ssoma hql optimization  ----------------------------------------------------------------------------  -------------------------  ------------------------- ---loading po line kpis data into po_so_dd_hu_details table for gpom model -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_mbp_nb -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2276 ssoma initial version -- 01.00.00.02 16oct19 scctp4-2523 ssoma changed partition columns and po for so model -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.04 05nov20 scctp-456 fyuan add fg filter ---------------------------------------------------------------------------  ------------------------- ---loading po line kpis data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details for mast beauty production;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_mbp_vsd_gs -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master,location_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2931 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ---------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_tkvsd -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, inventory_movement ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 27dec19 scctp4-3287 ssoma turnkey production to vsd initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ---------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_ven_rfc -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master,location_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2931 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ---------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_vendor_to_dc -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, inventory_movement ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 27dec19 scctp4-2996 ssoma component inflow initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ---------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_vsdinflow -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 06jan20 scctp4-3287 ssoma vsd inflow initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ----------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_vss_vsd -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 06jan20 scctp4-2924 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.03 04may20 scctp4-3331 ssoma hql optimization  ----------------------------------------------------------------------------   ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_vtptobdc_nb -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, inventory_movement ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 27dec19 scctp4-2901 ssoma turnkey production to brand initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter ---------------------------------------------------------------------------  ------------------------- ---loading po line kpis data into po_so_dd_hu_details table for vendor turnkey production -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_details_zdtd -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug20 scctp5-327 fyuan zdtd initial version ---------------------------------------------------------------------------- ------------------------- ---loading po line kpi's data into po_so_dd_hu_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_details;
! echo completed po_so_dd_hu_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_kpi_details_po -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_kpi_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2276 ssoma initial version -- 01.00.00.02 09oct19 scctp4-2523 ssoma changed partition columns and added new column -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.04 05nov20 scctp-456 fyuan add component filter  --------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_kpi_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_kpi_details;
! echo completed po_so_dd_hu_kpi_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_kpi_details_podd -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_kpi_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2276 ssoma initial version -- 01.00.00.02 09oct19 scctp4-2523 ssoma changed partition columns and added new column -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.03 20aug20 scctp5-327 fyuan add zdtd  --------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_kpi_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_kpi_details;
! echo completed po_so_dd_hu_kpi_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_kpi_details_posodd -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_kpi_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2276 ssoma initial version -- 01.00.00.02 09oct19 scctp4-2523 ssoma changed partition columns and added new column -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter --------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_kpi_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_kpi_details;
! echo completed po_so_dd_hu_kpi_details data load;
---jobname:scct-ufposo-hive-stg1-po_so_dd_hu_kpi_details_sodd -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_so_dd_hu_kpi_details  ---source: tms_stage0 table : po_master, delivery_master, inventory_movement,  ---handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 20aug19 scctp4-2276 ssoma initial version -- 01.00.00.02 09oct19 scctp4-2523 ssoma changed partition columns and added new column -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter --------------------------------------------------------------------------  ------------------------- ---loading po line kpi's data into po_so_dd_hu_kpi_details table -------------------------  ! echo started loading into scct_db.po_so_dd_hu_kpi_details;
! echo completed po_so_dd_hu_kpi_details data load;
---jobname:scct-e2e_dashboard-hive-stg1-scct_db.prepack_component -------------------------------------------------------------------------- ---target: stage1 table: scct_db.prepack_component  ---source: scct_db table : bom_item, bom_detail, analytics_view table : item ---load type: full ---back posting: no ---author: ryadav ---last modified date: 12/18/2018 --------------------------------------------------------------------------  ------------------------- ---loading prepack_component stage 1 base data -------------------------  ! echo started loading into scct_db.prepack_component ;
INSERT OVERWRITE INTO SCCT_DB.PREPACK_COMPONENT
(SELECT COALESCE(CASE WHEN TRIM( A.BOM_ITEM_NBR) = '' THEN NULL ELSE TRIM( A.BOM_ITEM_NBR) END, 'n/a') AS PPCK_ITM_NBR, COALESCE(CASE WHEN TRIM( B.BOM_CPNT_ITEM_NBR) = '' THEN NULL ELSE TRIM( B.BOM_CPNT_ITEM_NBR) END, 'n/a') AS PPCK_CPNT_ITM_NBR, COALESCE(CASE WHEN B.BOM_CPNT_QTY = '' THEN NULL ELSE B.BOM_CPNT_QTY END, 0.00) AS PPCK_CPNT_ITEM_QTY, COALESCE(CASE WHEN TRIM( B.BOM_CPNT_UNT_OF_MEAS_CD) = '' THEN NULL ELSE TRIM( B.BOM_CPNT_UNT_OF_MEAS_CD) END, 'n/a') AS PPCK_CPNT_UNT_OF_MEAS
FROM SCCT_DB.BOM_ITEM AS A
INNER JOIN SCCT_DB.BOM_DETAIL AS B ON A.BOM_NBR = B.BOM_NBR
INNER JOIN ANALYTICS_VIEW.ITEM AS C ON A.BOM_ITEM_NBR = C.ITEM_NUMBER
WHERE C.ITEM_TYPE_CODE = 'zpre'
GROUP BY A.BOM_ITEM_NBR, B.BOM_CPNT_ITEM_NBR, B.BOM_CPNT_QTY, B.BOM_CPNT_UNT_OF_MEAS_CD);
