! echo completed loading into scct_db.scem_expected_events;
---jobname:scct-scem-hive-stg1-scct_db.scem_tracking_events -------------------------------------------------------------------------- ---target: stage1 table: scct_db.scem_tracking_events  ---source: sap_stage0 table : scem_tracking_events_tmp ---description: this script will load the delta data to target table scct_db.scem_tracking_events ---load type: full ---back posting: no --------------------------------------------------------------------------  -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ ---------------------------- -- 01.00.00.01 23jul19 sdhal initial version -- 01.00.00.02 06sep19 scctp4-2187 akoti changed patition key to eh_created_date and added logic to ignore records where di_operation_type <> 'd' -- 01.00.00.03 29nov19 scctp4-2623 akoti removed partition column & settings, changed di_operation_type logic --  ------------------------- ---job related hive settings to merge files for target table ------------------------- set hive.merge.orcfile.stripe.level=false;
------------------------- ---loading scem_tracking_events target table data -------------------------  set tez.job.name=stage2:scem_tracking_events :load target table scem_tracking_events ;
! echo started loading into scct_db.scem_tracking_events ;
! echo completed loading into scct_db.scem_tracking_events ;
---jobname:scct-scem-hive-stg1-scct_db.scem_tracking_objects -------------------------------------------------------------------------- ---target: stage1 table: scct_db.scem_tracking_objects  ---source: scct_work_db table : scem_tracking_objects_tmp ---description: this script will load the delta data to target table scct_db.scem_tracking_objects ---load type: full ---back posting: no ---author: sdhal ---created date: 29/07/2019 -------------------------------------------------------------------------- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ ---------------------------- -- 01.00.00.01 29jul19 sdhal initial version -- 01.00.00.02 06sep19 scctp4-2187 akoti added logic to ignore records where di_operation_type <> 'd' -- 01.00.00.03 19sep19 scctp4-2460 ryadav increased tez container size -- 01.00.00.04 29nov19 scctp4-2623 akoti removed partition column & settings, changed di_operation_type logic -- 01.00.00.05 21jan20 scctp4-2988 akoti changed column name from act_po_gr_date to act_gac_date --  ------------------------- ---job related hive settings to merge files for target table -------------------------  set hive.merge.orcfile.stripe.level=false;
------------------------- ---loading scem_tracking_objects target table data -------------------------  set tez.job.name=stage2:scem_tracking_objects :load target table scem_tracking_objects ;
! echo started loading into scct_db.scem_tracking_objects ;
! echo completed loading into scct_db.scem_tracking_objects ;
---jobname:scct-scem-hive-stg1-scct_db.scem_tracking_types -------------------------------------------------------------------------- ---target: stage1 table: scct_db.scem_tracking_types  ---source: scct_work_db table : scem_tracking_types_temp, scct_db table : scem_tracking_types ---load type: full ---back posting: no ---author: ryadav ---created date: 03/14/2019 --------------------------------------------------------------------------   ------------------------- ---job related hive settings to merge files for target table -------------------------  set hive.merge.orcfile.stripe.level=false;
------------------------- ---loading scem_tracking_types target table data -------------------------  set tez.job.name=stage1:scem_tracking_types :load target table scem_tracking_types ;
! echo started loading into scct_db.scem_tracking_types ;
! echo completed loading into scct_db.scem_tracking_types ;
---jobname:scct-ufposo-hive-stg1-so_line_kpi_dcb_to_dcm_aprl -------------------------------------------------------------------------- ---target: stage1 table: scct_db.so_line_kpi  ---source: tms_stage0 table : delivery_master, handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 07jan20 scctp4-2924 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter --------------------------------------------------------------------------  ------------------------- ---job related hive settings  -------------------------   set hive.auto.convert.join.noconditionaltask.size=200000000;
------------------------- ---loading dd line kpi's data into so_line_kpi table -------------------------  set tez.job.name=load dd line kpis:so_line_kpi :load target from delivery_master ;
! echo started loading into scct_db.so_line_kpi;
! echo completed so_line_kpi data load;
---jobname:scct-usposo-hive-stg1-so_line_kpi_dcoutboundso -------------------------------------------------------------------------- ---target: stage1 table: scct_db.so_line_kpi  ---source: tms_stage0 table : delivery_master, handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 07jan20 scctp4-2924 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter --------------------------------------------------------------------------  ------------------------- ---job related hive settings  -------------------------   set hive.auto.convert.join.noconditionaltask.size=200000000;
------------------------- ---loading dd line kpi's data into so_line_kpi table -------------------------  set tez.job.name=load dd line kpis:so_line_kpi :load target from delivery_master ;
! echo started loading into scct_db.so_line_kpi;
! echo completed so_line_kpi data load;
---jobname:scct-ufposo-hive-stg1-so_line_kpi_final -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_line_kpi  ---source: tms_stage0 table : so_line_kpi_work and so_line_kpi_work1 ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 04may20 scctp4-2922 ssoma initial version ---------------------------------------------------------------------------  ------------------------- ---job related hive settings  -------------------------  set mapreduce.job.reduces=200;
------------------------- ---loading po line kpi's data into dd_line_kpi table -------------------------  set tez.job.name=load po line kpis:so_line_kpi:load target from po_master ;
! echo started loading scct_work_db.so_line_kpi_work1 for all the modules;
! echo started loading scct_work_db.so_line_kpi_work for all the modules;
! echo completed so_line_kpi data load;
---jobname:scct-ufposo-hive-stg1-so_line_kpi_vss_to_vsd -------------------------------------------------------------------------- ---target: stage1 table: scct_db.so_line_kpi  ---source: tms_stage0 table : delivery_master, handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 07jan20 scctp4-2924 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.03 04may20 scctp4-3331 ssoma hql optimization  --------------------------------------------------------------------------  ------------------------- ---job related hive settings  -------------------------    set hive.auto.convert.join.noconditionaltask.size=200000000;
------------------------- ---loading dd line kpi's data into so_line_kpi table -------------------------  set tez.job.name=load dd line kpis:so_line_kpi :load target from delivery_master ;
! echo started loading into scct_db.so_line_kpi;
! echo completed so_line_kpi data load;
---jobname:scct-masterdata-hive-stg1-scct_db.so_master -------------------------------------------------------------------------- ---target: stage1 table: so_master ---source: scct_raw_db.maprdb_vbak_raw, scct_raw_db.vbpa_raw, scct_raw_db.maprdb_vbap_raw ---load type: delta ---back posting: no -------------------------------------------------------------------------  -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ ---------------------------- -- 01.00.00.01 23may19 ssoma initial version -- 01.00.00.02 23sep19 scctp4-2471 ryadav mapr remediation changes for column names, item and location length -- 01.00.00.03 26sep19 scctp4-2481 ryadav added lpad in location join -- 01.00.00.04 04nov19 scctp4-2638 ssoma added cust_prch_itm_nbr(posex) column into so_master -- 01.00.00.05 03jun20 scctp4-1777 ashettap added chngind column into so_master -- 01.00.00.06 03jul20 scctp5-217 ashettap added 9 columns from sls_distr_doc_nbr through overall_sls_ord_blk_stat to so_master  ------------------------- ---job related hive settings to read huge dataset and merge files for target table -------------------------  set hive.auto.convert.join.noconditionaltask.size=3000000000;
------------------------- ---loading so_master stage 1 base table -------------------------  set tez.job.name=stage1:load_so_master:load_so_master;
! echo started loading into scct_db.so_master;
INSERT OVERWRITE INTO SCCT_DB.SO_MASTER
(SELECT SLS_ORD_NBR, SLS_ORD_ITM_NBR, ITM_NBR, DELIV_ITM_CAT, REJ_RSN, PROD_HIER, DOC_CURRCY_VAL, TGT_SLS_UNT_QTY, TGT_QTY_UOM, CONVN_FCT_1, CONVN_FCT_2, BASE_UOM, NET_VAL, CURRCY, ORD_QTY_SLS_UNT, REQ_DELIV_QTY_SLS_UNT, CONFRMD_QTY_SLS_UNT, CONFRMD_QTY_BASE_UNT, SLS_UNT, NUM_CONVN, DENOM_CONVN, GRS_WGT, NET_WGT, WGT_UNT, VOL, VOL_UNT, ORIGTG_DOC, ORIGTG_ITM, REF_ITM_NBR, DELIV_PRTY, COALESCE(RCVL.LOCATION_NUMBER, TMP.RECV_LOC_NBR), COALESCE(SRL.LOCATION_NUMBER, TMP.SHIP_RECV_LOC_NBR), REC_CRTD_DT, REC_CRTD_ID, REC_ENTR_TM, NET_PRC, COND_PRC_UNT, COND_UOM, COST, PRC_COND_SUBT_1, PRC_COND_SUBT_2, PRC_COND_SUBT_3, PRC_COND_SUBT_4, PRC_COND_SUBT_5, PRC_COND_SUBT_6, EXCHG_RT_STATS, REC_CHGD_DT, PCTR, SPEC_STK_IND, PRFT_SEG, CONVN_FCT, REQMS_TYPE, ITM_CR_PRC, ACTV_CR_FUNC, CR_EXCHG_RT, CNFGRN_INTRNL_OBJ_NBR, CUST_CLS, CUST_STYLE, STYLE_DESC, ORIG_QTY, ORIG_UOM, ORIG_ITM_PRC, ORIG_CUST_ITM_PRC, REV_CUST_ITM_PRC, CNCL_DT, DN_SHP_DT, CUST_DEPT_CD, DOC_DT, SLS_DOC_CAT, TRANS_GRP, SLS_DOC_TYPE, ORD_RSN, SLS_DOC_CRCY, SLS_ORG, DISTR_CHNL, DIVISION, SLS_GRP, SLS_OFC, NBR_DOC_COND, REQSTD_DT, PRPSD_DT_TYPE, PROC, SHP_COND, SLS_PROB, CUST_PRCH_NBR, CUST_ORD_TYPE, CUST_PRCH_ORD_DT, NBR_CNTC_CUST, CUST_NBR, UPD_STATS_GRP, STATS_CRCY, CNTLG_AREA, CR_CNTL_AREA, CR_RSK, CR_VAL_CRCY, RLSED_CR_VAL_DOC, HIER_TYPE_PRC, CO_CD_BILLD, REF_DOC_NBR, ARTCL_AVAIL_DT, GUID_KEY, TOT_ORD_QTY, ORIG_TOT_PRC, REV_TOT_PRC, CPO_STAT, CPO_TYPE, MAST_NBR, PRE_TICKT, MEDIA_CD, COALESCE(SHPL.LOCATION_NUMBER, TMP.SHIP_TO_LOC_NBR), CNTRY_CD, SHP_TO_DESC, PARTN_FUNC, RNDG_QTY, PURCH_ORD_ITM_NBR, DELV_GRP, QTY_FIXD, UNLTD_OD, OD_TOLNC, UND_DELV_TOLNC, BTCH_SPLT_ALWD, REF_DOC_NBR_DTL, COMPL_REF, ROUTE, INTNL_PROD_NBR, CMPNT_QLTY, CUST_LNG_SKU, MAST_STYLE_NBR, CUST_COLOR_CD, CUST_COLOR_DESC, CUST_SZ_CD, CO_SZ_DESC, PRE_PACK_MSTR_SKU, PRE_PACK_SORT_CD, ORIG_NDC_DT, DN_SHP_ERLR_DT, CUST_GARMENT_CLS, VEND_STYLE_CD, PRE_PACK_CD, PACK_TYPE, GAC_DT, PACK_CNT, CORSP_ARTCL_NBR_SHRD, REC_CRTD_DT_HDR, REC_CRTD_ID_HDR, DELV_BLK, BLLG_BLK, REC_CHGD_DT_HDR, REF_DOC_NBR_HDR, CNTNS_DG, COORIG_CD, CUST_PRCH_ITM_NBR, DEL_IND, SLS_ORD_ITM_DELV_DT, SLS_ORD_ITM_REQ_DT, SLS_ORD_ITM_RSRVN_DT, SLS_ORD_ITM_PKG_RTRN_DT, SLS_ORD_ITM_TRANSP_PLNG_DT, SLS_ORD_ITM_MTRL_STNG_DT, SLS_ORD_ITM_LOADG_DT, SLS_ORD_ITM_GDS_ISS_DT, SLS_ORD_ITM_ARRIV_TM, SLS_ORD_ITM_DT_TYP, SLS_DISTR_DOC_NBR, SLS_ORD_DEL_STAT, OVERALL_SLS_ORD_DEL_STAT_ALL_ITM, OVERALL_REJCT_STAT_ALL_SLS_DOC_ITM, OVERALL_DOC_PRCSSG_STAT, OVERALL_CR_CK_STAT, OVERALL_BILLG_BLK_STAT, OVERALL_SLS_ORD_DEL_BLK_STAT, OVERALL_SLS_ORD_BLK_STAT
FROM SCCT_WORK_DB.SO_MASTER_TMP AS TMP
LEFT JOIN (SELECT LOCATION_NUMBER
FROM ANALYTICS_DB.LOCATION
WHERE LOCATION_TYPE_CODE = '04') AS SHPL ON LPAD(TMP.SHIP_TO_LOC_NBR, 10, 0) = SHPL.LOCATION_NUMBER
LEFT JOIN (SELECT LOCATION_NUMBER
FROM ANALYTICS_DB.LOCATION
WHERE LOCATION_TYPE_CODE = '04') AS RCVL ON LPAD(TMP.RECV_LOC_NBR, 10, 0) = RCVL.LOCATION_NUMBER
LEFT JOIN (SELECT LOCATION_NUMBER
FROM ANALYTICS_DB.LOCATION
WHERE LOCATION_TYPE_CODE = '04') AS SRL ON LPAD(TMP.SHIP_RECV_LOC_NBR, 10, 0) = SRL.LOCATION_NUMBER);
! echo completed loading into scct_db.scem_expected_events;
---jobname:scct-scem-hive-stg1-scct_db.scem_tracking_events -------------------------------------------------------------------------- ---target: stage1 table: scct_db.scem_tracking_events  ---source: sap_stage0 table : scem_tracking_events_tmp ---description: this script will load the delta data to target table scct_db.scem_tracking_events ---load type: full ---back posting: no --------------------------------------------------------------------------  -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ ---------------------------- -- 01.00.00.01 23jul19 sdhal initial version -- 01.00.00.02 06sep19 scctp4-2187 akoti changed patition key to eh_created_date and added logic to ignore records where di_operation_type <> 'd' -- 01.00.00.03 29nov19 scctp4-2623 akoti removed partition column & settings, changed di_operation_type logic --  ------------------------- ---job related hive settings to merge files for target table ------------------------- set hive.merge.orcfile.stripe.level=false;
------------------------- ---loading scem_tracking_events target table data -------------------------  set tez.job.name=stage2:scem_tracking_events :load target table scem_tracking_events ;
! echo started loading into scct_db.scem_tracking_events ;
! echo completed loading into scct_db.scem_tracking_events ;
---jobname:scct-scem-hive-stg1-scct_db.scem_tracking_objects -------------------------------------------------------------------------- ---target: stage1 table: scct_db.scem_tracking_objects  ---source: scct_work_db table : scem_tracking_objects_tmp ---description: this script will load the delta data to target table scct_db.scem_tracking_objects ---load type: full ---back posting: no ---author: sdhal ---created date: 29/07/2019 -------------------------------------------------------------------------- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ ---------------------------- -- 01.00.00.01 29jul19 sdhal initial version -- 01.00.00.02 06sep19 scctp4-2187 akoti added logic to ignore records where di_operation_type <> 'd' -- 01.00.00.03 19sep19 scctp4-2460 ryadav increased tez container size -- 01.00.00.04 29nov19 scctp4-2623 akoti removed partition column & settings, changed di_operation_type logic -- 01.00.00.05 21jan20 scctp4-2988 akoti changed column name from act_po_gr_date to act_gac_date --  ------------------------- ---job related hive settings to merge files for target table -------------------------  set hive.merge.orcfile.stripe.level=false;
------------------------- ---loading scem_tracking_objects target table data -------------------------  set tez.job.name=stage2:scem_tracking_objects :load target table scem_tracking_objects ;
! echo started loading into scct_db.scem_tracking_objects ;
! echo completed loading into scct_db.scem_tracking_objects ;
---jobname:scct-scem-hive-stg1-scct_db.scem_tracking_types -------------------------------------------------------------------------- ---target: stage1 table: scct_db.scem_tracking_types  ---source: scct_work_db table : scem_tracking_types_temp, scct_db table : scem_tracking_types ---load type: full ---back posting: no ---author: ryadav ---created date: 03/14/2019 --------------------------------------------------------------------------   ------------------------- ---job related hive settings to merge files for target table -------------------------  set hive.merge.orcfile.stripe.level=false;
------------------------- ---loading scem_tracking_types target table data -------------------------  set tez.job.name=stage1:scem_tracking_types :load target table scem_tracking_types ;
! echo started loading into scct_db.scem_tracking_types ;
! echo completed loading into scct_db.scem_tracking_types ;
---jobname:scct-ufposo-hive-stg1-so_line_kpi_dcb_to_dcm_aprl -------------------------------------------------------------------------- ---target: stage1 table: scct_db.so_line_kpi  ---source: tms_stage0 table : delivery_master, handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 07jan20 scctp4-2924 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter --------------------------------------------------------------------------  ------------------------- ---job related hive settings  -------------------------   set hive.auto.convert.join.noconditionaltask.size=200000000;
------------------------- ---loading dd line kpi's data into so_line_kpi table -------------------------  set tez.job.name=load dd line kpis:so_line_kpi :load target from delivery_master ;
! echo started loading into scct_db.so_line_kpi;
! echo completed so_line_kpi data load;
---jobname:scct-usposo-hive-stg1-so_line_kpi_dcoutboundso -------------------------------------------------------------------------- ---target: stage1 table: scct_db.so_line_kpi  ---source: tms_stage0 table : delivery_master, handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 07jan20 scctp4-2924 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter --------------------------------------------------------------------------  ------------------------- ---job related hive settings  -------------------------   set hive.auto.convert.join.noconditionaltask.size=200000000;
------------------------- ---loading dd line kpi's data into so_line_kpi table -------------------------  set tez.job.name=load dd line kpis:so_line_kpi :load target from delivery_master ;
! echo started loading into scct_db.so_line_kpi;
! echo completed so_line_kpi data load;
---jobname:scct-ufposo-hive-stg1-so_line_kpi_final -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_line_kpi  ---source: tms_stage0 table : so_line_kpi_work and so_line_kpi_work1 ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 04may20 scctp4-2922 ssoma initial version ---------------------------------------------------------------------------  ------------------------- ---job related hive settings  -------------------------  set mapreduce.job.reduces=200;
------------------------- ---loading po line kpi's data into dd_line_kpi table -------------------------  set tez.job.name=load po line kpis:so_line_kpi:load target from po_master ;
! echo started loading scct_work_db.so_line_kpi_work1 for all the modules;
! echo started loading scct_work_db.so_line_kpi_work for all the modules;
! echo completed so_line_kpi data load;
---jobname:scct-ufposo-hive-stg1-so_line_kpi_vss_to_vsd -------------------------------------------------------------------------- ---target: stage1 table: scct_db.so_line_kpi  ---source: tms_stage0 table : delivery_master, handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 07jan20 scctp4-2924 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.03 04may20 scctp4-3331 ssoma hql optimization  --------------------------------------------------------------------------  ------------------------- ---job related hive settings  -------------------------    set hive.auto.convert.join.noconditionaltask.size=200000000;
------------------------- ---loading dd line kpi's data into so_line_kpi table -------------------------  set tez.job.name=load dd line kpis:so_line_kpi :load target from delivery_master ;
! echo started loading into scct_db.so_line_kpi;
! echo completed so_line_kpi data load;
---jobname:scct-masterdata-hive-stg1-scct_db.so_master -------------------------------------------------------------------------- ---target: stage1 table: so_master ---source: scct_raw_db.maprdb_vbak_raw, scct_raw_db.vbpa_raw, scct_raw_db.maprdb_vbap_raw ---load type: delta ---back posting: no -------------------------------------------------------------------------  -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ ---------------------------- -- 01.00.00.01 23may19 ssoma initial version -- 01.00.00.02 23sep19 scctp4-2471 ryadav mapr remediation changes for column names, item and location length -- 01.00.00.03 26sep19 scctp4-2481 ryadav added lpad in location join -- 01.00.00.04 04nov19 scctp4-2638 ssoma added cust_prch_itm_nbr(posex) column into so_master -- 01.00.00.05 03jun20 scctp4-1777 ashettap added chngind column into so_master -- 01.00.00.06 03jul20 scctp5-217 ashettap added 9 columns from sls_distr_doc_nbr through overall_sls_ord_blk_stat to so_master  ------------------------- ---job related hive settings to read huge dataset and merge files for target table -------------------------  set hive.auto.convert.join.noconditionaltask.size=3000000000;
------------------------- ---loading so_master stage 1 base table -------------------------  set tez.job.name=stage1:load_so_master:load_so_master;
! echo started loading into scct_db.so_master;
INSERT OVERWRITE INTO SCCT_DB.SO_MASTER
(SELECT SLS_ORD_NBR, SLS_ORD_ITM_NBR, ITM_NBR, DELIV_ITM_CAT, REJ_RSN, PROD_HIER, DOC_CURRCY_VAL, TGT_SLS_UNT_QTY, TGT_QTY_UOM, CONVN_FCT_1, CONVN_FCT_2, BASE_UOM, NET_VAL, CURRCY, ORD_QTY_SLS_UNT, REQ_DELIV_QTY_SLS_UNT, CONFRMD_QTY_SLS_UNT, CONFRMD_QTY_BASE_UNT, SLS_UNT, NUM_CONVN, DENOM_CONVN, GRS_WGT, NET_WGT, WGT_UNT, VOL, VOL_UNT, ORIGTG_DOC, ORIGTG_ITM, REF_ITM_NBR, DELIV_PRTY, COALESCE(RCVL.LOCATION_NUMBER, TMP.RECV_LOC_NBR), COALESCE(SRL.LOCATION_NUMBER, TMP.SHIP_RECV_LOC_NBR), REC_CRTD_DT, REC_CRTD_ID, REC_ENTR_TM, NET_PRC, COND_PRC_UNT, COND_UOM, COST, PRC_COND_SUBT_1, PRC_COND_SUBT_2, PRC_COND_SUBT_3, PRC_COND_SUBT_4, PRC_COND_SUBT_5, PRC_COND_SUBT_6, EXCHG_RT_STATS, REC_CHGD_DT, PCTR, SPEC_STK_IND, PRFT_SEG, CONVN_FCT, REQMS_TYPE, ITM_CR_PRC, ACTV_CR_FUNC, CR_EXCHG_RT, CNFGRN_INTRNL_OBJ_NBR, CUST_CLS, CUST_STYLE, STYLE_DESC, ORIG_QTY, ORIG_UOM, ORIG_ITM_PRC, ORIG_CUST_ITM_PRC, REV_CUST_ITM_PRC, CNCL_DT, DN_SHP_DT, CUST_DEPT_CD, DOC_DT, SLS_DOC_CAT, TRANS_GRP, SLS_DOC_TYPE, ORD_RSN, SLS_DOC_CRCY, SLS_ORG, DISTR_CHNL, DIVISION, SLS_GRP, SLS_OFC, NBR_DOC_COND, REQSTD_DT, PRPSD_DT_TYPE, PROC, SHP_COND, SLS_PROB, CUST_PRCH_NBR, CUST_ORD_TYPE, CUST_PRCH_ORD_DT, NBR_CNTC_CUST, CUST_NBR, UPD_STATS_GRP, STATS_CRCY, CNTLG_AREA, CR_CNTL_AREA, CR_RSK, CR_VAL_CRCY, RLSED_CR_VAL_DOC, HIER_TYPE_PRC, CO_CD_BILLD, REF_DOC_NBR, ARTCL_AVAIL_DT, GUID_KEY, TOT_ORD_QTY, ORIG_TOT_PRC, REV_TOT_PRC, CPO_STAT, CPO_TYPE, MAST_NBR, PRE_TICKT, MEDIA_CD, COALESCE(SHPL.LOCATION_NUMBER, TMP.SHIP_TO_LOC_NBR), CNTRY_CD, SHP_TO_DESC, PARTN_FUNC, RNDG_QTY, PURCH_ORD_ITM_NBR, DELV_GRP, QTY_FIXD, UNLTD_OD, OD_TOLNC, UND_DELV_TOLNC, BTCH_SPLT_ALWD, REF_DOC_NBR_DTL, COMPL_REF, ROUTE, INTNL_PROD_NBR, CMPNT_QLTY, CUST_LNG_SKU, MAST_STYLE_NBR, CUST_COLOR_CD, CUST_COLOR_DESC, CUST_SZ_CD, CO_SZ_DESC, PRE_PACK_MSTR_SKU, PRE_PACK_SORT_CD, ORIG_NDC_DT, DN_SHP_ERLR_DT, CUST_GARMENT_CLS, VEND_STYLE_CD, PRE_PACK_CD, PACK_TYPE, GAC_DT, PACK_CNT, CORSP_ARTCL_NBR_SHRD, REC_CRTD_DT_HDR, REC_CRTD_ID_HDR, DELV_BLK, BLLG_BLK, REC_CHGD_DT_HDR, REF_DOC_NBR_HDR, CNTNS_DG, COORIG_CD, CUST_PRCH_ITM_NBR, DEL_IND, SLS_ORD_ITM_DELV_DT, SLS_ORD_ITM_REQ_DT, SLS_ORD_ITM_RSRVN_DT, SLS_ORD_ITM_PKG_RTRN_DT, SLS_ORD_ITM_TRANSP_PLNG_DT, SLS_ORD_ITM_MTRL_STNG_DT, SLS_ORD_ITM_LOADG_DT, SLS_ORD_ITM_GDS_ISS_DT, SLS_ORD_ITM_ARRIV_TM, SLS_ORD_ITM_DT_TYP, SLS_DISTR_DOC_NBR, SLS_ORD_DEL_STAT, OVERALL_SLS_ORD_DEL_STAT_ALL_ITM, OVERALL_REJCT_STAT_ALL_SLS_DOC_ITM, OVERALL_DOC_PRCSSG_STAT, OVERALL_CR_CK_STAT, OVERALL_BILLG_BLK_STAT, OVERALL_SLS_ORD_DEL_BLK_STAT, OVERALL_SLS_ORD_BLK_STAT
FROM SCCT_WORK_DB.SO_MASTER_TMP AS TMP
LEFT JOIN (SELECT LOCATION_NUMBER
FROM ANALYTICS_DB.LOCATION
WHERE LOCATION_TYPE_CODE = '04') AS SHPL ON LPAD(TMP.SHIP_TO_LOC_NBR, 10, 0) = SHPL.LOCATION_NUMBER
LEFT JOIN (SELECT LOCATION_NUMBER
FROM ANALYTICS_DB.LOCATION
WHERE LOCATION_TYPE_CODE = '04') AS RCVL ON LPAD(TMP.RECV_LOC_NBR, 10, 0) = RCVL.LOCATION_NUMBER
LEFT JOIN (SELECT LOCATION_NUMBER
FROM ANALYTICS_DB.LOCATION
WHERE LOCATION_TYPE_CODE = '04') AS SRL ON LPAD(TMP.SHIP_RECV_LOC_NBR, 10, 0) = SRL.LOCATION_NUMBER);
! echo completed loading into scct_db.scem_expected_events;
---jobname:scct-scem-hive-stg1-scct_db.scem_tracking_events -------------------------------------------------------------------------- ---target: stage1 table: scct_db.scem_tracking_events  ---source: sap_stage0 table : scem_tracking_events_tmp ---description: this script will load the delta data to target table scct_db.scem_tracking_events ---load type: full ---back posting: no --------------------------------------------------------------------------  -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ ---------------------------- -- 01.00.00.01 23jul19 sdhal initial version -- 01.00.00.02 06sep19 scctp4-2187 akoti changed patition key to eh_created_date and added logic to ignore records where di_operation_type <> 'd' -- 01.00.00.03 29nov19 scctp4-2623 akoti removed partition column & settings, changed di_operation_type logic --  ------------------------- ---job related hive settings to merge files for target table ------------------------- set hive.merge.orcfile.stripe.level=false;
------------------------- ---loading scem_tracking_events target table data -------------------------  set tez.job.name=stage2:scem_tracking_events :load target table scem_tracking_events ;
! echo started loading into scct_db.scem_tracking_events ;
! echo completed loading into scct_db.scem_tracking_events ;
---jobname:scct-scem-hive-stg1-scct_db.scem_tracking_objects -------------------------------------------------------------------------- ---target: stage1 table: scct_db.scem_tracking_objects  ---source: scct_work_db table : scem_tracking_objects_tmp ---description: this script will load the delta data to target table scct_db.scem_tracking_objects ---load type: full ---back posting: no ---author: sdhal ---created date: 29/07/2019 -------------------------------------------------------------------------- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ ---------------------------- -- 01.00.00.01 29jul19 sdhal initial version -- 01.00.00.02 06sep19 scctp4-2187 akoti added logic to ignore records where di_operation_type <> 'd' -- 01.00.00.03 19sep19 scctp4-2460 ryadav increased tez container size -- 01.00.00.04 29nov19 scctp4-2623 akoti removed partition column & settings, changed di_operation_type logic -- 01.00.00.05 21jan20 scctp4-2988 akoti changed column name from act_po_gr_date to act_gac_date --  ------------------------- ---job related hive settings to merge files for target table -------------------------  set hive.merge.orcfile.stripe.level=false;
------------------------- ---loading scem_tracking_objects target table data -------------------------  set tez.job.name=stage2:scem_tracking_objects :load target table scem_tracking_objects ;
! echo started loading into scct_db.scem_tracking_objects ;
! echo completed loading into scct_db.scem_tracking_objects ;
---jobname:scct-scem-hive-stg1-scct_db.scem_tracking_types -------------------------------------------------------------------------- ---target: stage1 table: scct_db.scem_tracking_types  ---source: scct_work_db table : scem_tracking_types_temp, scct_db table : scem_tracking_types ---load type: full ---back posting: no ---author: ryadav ---created date: 03/14/2019 --------------------------------------------------------------------------   ------------------------- ---job related hive settings to merge files for target table -------------------------  set hive.merge.orcfile.stripe.level=false;
------------------------- ---loading scem_tracking_types target table data -------------------------  set tez.job.name=stage1:scem_tracking_types :load target table scem_tracking_types ;
! echo started loading into scct_db.scem_tracking_types ;
! echo completed loading into scct_db.scem_tracking_types ;
---jobname:scct-ufposo-hive-stg1-so_line_kpi_dcb_to_dcm_aprl -------------------------------------------------------------------------- ---target: stage1 table: scct_db.so_line_kpi  ---source: tms_stage0 table : delivery_master, handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 07jan20 scctp4-2924 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter --------------------------------------------------------------------------  ------------------------- ---job related hive settings  -------------------------   set hive.auto.convert.join.noconditionaltask.size=200000000;
------------------------- ---loading dd line kpi's data into so_line_kpi table -------------------------  set tez.job.name=load dd line kpis:so_line_kpi :load target from delivery_master ;
! echo started loading into scct_db.so_line_kpi;
! echo completed so_line_kpi data load;
---jobname:scct-usposo-hive-stg1-so_line_kpi_dcoutboundso -------------------------------------------------------------------------- ---target: stage1 table: scct_db.so_line_kpi  ---source: tms_stage0 table : delivery_master, handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 07jan20 scctp4-2924 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter --------------------------------------------------------------------------  ------------------------- ---job related hive settings  -------------------------   set hive.auto.convert.join.noconditionaltask.size=200000000;
------------------------- ---loading dd line kpi's data into so_line_kpi table -------------------------  set tez.job.name=load dd line kpis:so_line_kpi :load target from delivery_master ;
! echo started loading into scct_db.so_line_kpi;
! echo completed so_line_kpi data load;
---jobname:scct-ufposo-hive-stg1-so_line_kpi_final -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_line_kpi  ---source: tms_stage0 table : so_line_kpi_work and so_line_kpi_work1 ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 04may20 scctp4-2922 ssoma initial version ---------------------------------------------------------------------------  ------------------------- ---job related hive settings  -------------------------  set mapreduce.job.reduces=200;
------------------------- ---loading po line kpi's data into dd_line_kpi table -------------------------  set tez.job.name=load po line kpis:so_line_kpi:load target from po_master ;
! echo started loading scct_work_db.so_line_kpi_work1 for all the modules;
! echo started loading scct_work_db.so_line_kpi_work for all the modules;
! echo completed so_line_kpi data load;
---jobname:scct-ufposo-hive-stg1-so_line_kpi_vss_to_vsd -------------------------------------------------------------------------- ---target: stage1 table: scct_db.so_line_kpi  ---source: tms_stage0 table : delivery_master, handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 07jan20 scctp4-2924 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.03 04may20 scctp4-3331 ssoma hql optimization  --------------------------------------------------------------------------  ------------------------- ---job related hive settings  -------------------------    set hive.auto.convert.join.noconditionaltask.size=200000000;
------------------------- ---loading dd line kpi's data into so_line_kpi table -------------------------  set tez.job.name=load dd line kpis:so_line_kpi :load target from delivery_master ;
! echo started loading into scct_db.so_line_kpi;
! echo completed so_line_kpi data load;
---jobname:scct-masterdata-hive-stg1-scct_db.so_master -------------------------------------------------------------------------- ---target: stage1 table: so_master ---source: scct_raw_db.maprdb_vbak_raw, scct_raw_db.vbpa_raw, scct_raw_db.maprdb_vbap_raw ---load type: delta ---back posting: no -------------------------------------------------------------------------  -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ ---------------------------- -- 01.00.00.01 23may19 ssoma initial version -- 01.00.00.02 23sep19 scctp4-2471 ryadav mapr remediation changes for column names, item and location length -- 01.00.00.03 26sep19 scctp4-2481 ryadav added lpad in location join -- 01.00.00.04 04nov19 scctp4-2638 ssoma added cust_prch_itm_nbr(posex) column into so_master -- 01.00.00.05 03jun20 scctp4-1777 ashettap added chngind column into so_master -- 01.00.00.06 03jul20 scctp5-217 ashettap added 9 columns from sls_distr_doc_nbr through overall_sls_ord_blk_stat to so_master  ------------------------- ---job related hive settings to read huge dataset and merge files for target table -------------------------  set hive.auto.convert.join.noconditionaltask.size=3000000000;
------------------------- ---loading so_master stage 1 base table -------------------------  set tez.job.name=stage1:load_so_master:load_so_master;
! echo started loading into scct_db.so_master;
INSERT OVERWRITE INTO SCCT_DB.SO_MASTER
(SELECT SLS_ORD_NBR, SLS_ORD_ITM_NBR, ITM_NBR, DELIV_ITM_CAT, REJ_RSN, PROD_HIER, DOC_CURRCY_VAL, TGT_SLS_UNT_QTY, TGT_QTY_UOM, CONVN_FCT_1, CONVN_FCT_2, BASE_UOM, NET_VAL, CURRCY, ORD_QTY_SLS_UNT, REQ_DELIV_QTY_SLS_UNT, CONFRMD_QTY_SLS_UNT, CONFRMD_QTY_BASE_UNT, SLS_UNT, NUM_CONVN, DENOM_CONVN, GRS_WGT, NET_WGT, WGT_UNT, VOL, VOL_UNT, ORIGTG_DOC, ORIGTG_ITM, REF_ITM_NBR, DELIV_PRTY, COALESCE(RCVL.LOCATION_NUMBER, TMP.RECV_LOC_NBR), COALESCE(SRL.LOCATION_NUMBER, TMP.SHIP_RECV_LOC_NBR), REC_CRTD_DT, REC_CRTD_ID, REC_ENTR_TM, NET_PRC, COND_PRC_UNT, COND_UOM, COST, PRC_COND_SUBT_1, PRC_COND_SUBT_2, PRC_COND_SUBT_3, PRC_COND_SUBT_4, PRC_COND_SUBT_5, PRC_COND_SUBT_6, EXCHG_RT_STATS, REC_CHGD_DT, PCTR, SPEC_STK_IND, PRFT_SEG, CONVN_FCT, REQMS_TYPE, ITM_CR_PRC, ACTV_CR_FUNC, CR_EXCHG_RT, CNFGRN_INTRNL_OBJ_NBR, CUST_CLS, CUST_STYLE, STYLE_DESC, ORIG_QTY, ORIG_UOM, ORIG_ITM_PRC, ORIG_CUST_ITM_PRC, REV_CUST_ITM_PRC, CNCL_DT, DN_SHP_DT, CUST_DEPT_CD, DOC_DT, SLS_DOC_CAT, TRANS_GRP, SLS_DOC_TYPE, ORD_RSN, SLS_DOC_CRCY, SLS_ORG, DISTR_CHNL, DIVISION, SLS_GRP, SLS_OFC, NBR_DOC_COND, REQSTD_DT, PRPSD_DT_TYPE, PROC, SHP_COND, SLS_PROB, CUST_PRCH_NBR, CUST_ORD_TYPE, CUST_PRCH_ORD_DT, NBR_CNTC_CUST, CUST_NBR, UPD_STATS_GRP, STATS_CRCY, CNTLG_AREA, CR_CNTL_AREA, CR_RSK, CR_VAL_CRCY, RLSED_CR_VAL_DOC, HIER_TYPE_PRC, CO_CD_BILLD, REF_DOC_NBR, ARTCL_AVAIL_DT, GUID_KEY, TOT_ORD_QTY, ORIG_TOT_PRC, REV_TOT_PRC, CPO_STAT, CPO_TYPE, MAST_NBR, PRE_TICKT, MEDIA_CD, COALESCE(SHPL.LOCATION_NUMBER, TMP.SHIP_TO_LOC_NBR), CNTRY_CD, SHP_TO_DESC, PARTN_FUNC, RNDG_QTY, PURCH_ORD_ITM_NBR, DELV_GRP, QTY_FIXD, UNLTD_OD, OD_TOLNC, UND_DELV_TOLNC, BTCH_SPLT_ALWD, REF_DOC_NBR_DTL, COMPL_REF, ROUTE, INTNL_PROD_NBR, CMPNT_QLTY, CUST_LNG_SKU, MAST_STYLE_NBR, CUST_COLOR_CD, CUST_COLOR_DESC, CUST_SZ_CD, CO_SZ_DESC, PRE_PACK_MSTR_SKU, PRE_PACK_SORT_CD, ORIG_NDC_DT, DN_SHP_ERLR_DT, CUST_GARMENT_CLS, VEND_STYLE_CD, PRE_PACK_CD, PACK_TYPE, GAC_DT, PACK_CNT, CORSP_ARTCL_NBR_SHRD, REC_CRTD_DT_HDR, REC_CRTD_ID_HDR, DELV_BLK, BLLG_BLK, REC_CHGD_DT_HDR, REF_DOC_NBR_HDR, CNTNS_DG, COORIG_CD, CUST_PRCH_ITM_NBR, DEL_IND, SLS_ORD_ITM_DELV_DT, SLS_ORD_ITM_REQ_DT, SLS_ORD_ITM_RSRVN_DT, SLS_ORD_ITM_PKG_RTRN_DT, SLS_ORD_ITM_TRANSP_PLNG_DT, SLS_ORD_ITM_MTRL_STNG_DT, SLS_ORD_ITM_LOADG_DT, SLS_ORD_ITM_GDS_ISS_DT, SLS_ORD_ITM_ARRIV_TM, SLS_ORD_ITM_DT_TYP, SLS_DISTR_DOC_NBR, SLS_ORD_DEL_STAT, OVERALL_SLS_ORD_DEL_STAT_ALL_ITM, OVERALL_REJCT_STAT_ALL_SLS_DOC_ITM, OVERALL_DOC_PRCSSG_STAT, OVERALL_CR_CK_STAT, OVERALL_BILLG_BLK_STAT, OVERALL_SLS_ORD_DEL_BLK_STAT, OVERALL_SLS_ORD_BLK_STAT
FROM SCCT_WORK_DB.SO_MASTER_TMP AS TMP
LEFT JOIN (SELECT LOCATION_NUMBER
FROM ANALYTICS_DB.LOCATION
WHERE LOCATION_TYPE_CODE = '04') AS SHPL ON LPAD(TMP.SHIP_TO_LOC_NBR, 10, 0) = SHPL.LOCATION_NUMBER
LEFT JOIN (SELECT LOCATION_NUMBER
FROM ANALYTICS_DB.LOCATION
WHERE LOCATION_TYPE_CODE = '04') AS RCVL ON LPAD(TMP.RECV_LOC_NBR, 10, 0) = RCVL.LOCATION_NUMBER
LEFT JOIN (SELECT LOCATION_NUMBER
FROM ANALYTICS_DB.LOCATION
WHERE LOCATION_TYPE_CODE = '04') AS SRL ON LPAD(TMP.SHIP_RECV_LOC_NBR, 10, 0) = SRL.LOCATION_NUMBER);
! echo completed loading into scct_db.scem_expected_events;
---jobname:scct-scem-hive-stg1-scct_db.scem_tracking_events -------------------------------------------------------------------------- ---target: stage1 table: scct_db.scem_tracking_events  ---source: sap_stage0 table : scem_tracking_events_tmp ---description: this script will load the delta data to target table scct_db.scem_tracking_events ---load type: full ---back posting: no --------------------------------------------------------------------------  -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ ---------------------------- -- 01.00.00.01 23jul19 sdhal initial version -- 01.00.00.02 06sep19 scctp4-2187 akoti changed patition key to eh_created_date and added logic to ignore records where di_operation_type <> 'd' -- 01.00.00.03 29nov19 scctp4-2623 akoti removed partition column & settings, changed di_operation_type logic --  ------------------------- ---job related hive settings to merge files for target table ------------------------- set hive.merge.orcfile.stripe.level=false;
------------------------- ---loading scem_tracking_events target table data -------------------------  set tez.job.name=stage2:scem_tracking_events :load target table scem_tracking_events ;
! echo started loading into scct_db.scem_tracking_events ;
! echo completed loading into scct_db.scem_tracking_events ;
---jobname:scct-scem-hive-stg1-scct_db.scem_tracking_objects -------------------------------------------------------------------------- ---target: stage1 table: scct_db.scem_tracking_objects  ---source: scct_work_db table : scem_tracking_objects_tmp ---description: this script will load the delta data to target table scct_db.scem_tracking_objects ---load type: full ---back posting: no ---author: sdhal ---created date: 29/07/2019 -------------------------------------------------------------------------- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ ---------------------------- -- 01.00.00.01 29jul19 sdhal initial version -- 01.00.00.02 06sep19 scctp4-2187 akoti added logic to ignore records where di_operation_type <> 'd' -- 01.00.00.03 19sep19 scctp4-2460 ryadav increased tez container size -- 01.00.00.04 29nov19 scctp4-2623 akoti removed partition column & settings, changed di_operation_type logic -- 01.00.00.05 21jan20 scctp4-2988 akoti changed column name from act_po_gr_date to act_gac_date --  ------------------------- ---job related hive settings to merge files for target table -------------------------  set hive.merge.orcfile.stripe.level=false;
------------------------- ---loading scem_tracking_objects target table data -------------------------  set tez.job.name=stage2:scem_tracking_objects :load target table scem_tracking_objects ;
! echo started loading into scct_db.scem_tracking_objects ;
! echo completed loading into scct_db.scem_tracking_objects ;
---jobname:scct-scem-hive-stg1-scct_db.scem_tracking_types -------------------------------------------------------------------------- ---target: stage1 table: scct_db.scem_tracking_types  ---source: scct_work_db table : scem_tracking_types_temp, scct_db table : scem_tracking_types ---load type: full ---back posting: no ---author: ryadav ---created date: 03/14/2019 --------------------------------------------------------------------------   ------------------------- ---job related hive settings to merge files for target table -------------------------  set hive.merge.orcfile.stripe.level=false;
------------------------- ---loading scem_tracking_types target table data -------------------------  set tez.job.name=stage1:scem_tracking_types :load target table scem_tracking_types ;
! echo started loading into scct_db.scem_tracking_types ;
! echo completed loading into scct_db.scem_tracking_types ;
---jobname:scct-ufposo-hive-stg1-so_line_kpi_dcb_to_dcm_aprl -------------------------------------------------------------------------- ---target: stage1 table: scct_db.so_line_kpi  ---source: tms_stage0 table : delivery_master, handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 07jan20 scctp4-2924 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter --------------------------------------------------------------------------  ------------------------- ---job related hive settings  -------------------------   set hive.auto.convert.join.noconditionaltask.size=200000000;
------------------------- ---loading dd line kpi's data into so_line_kpi table -------------------------  set tez.job.name=load dd line kpis:so_line_kpi :load target from delivery_master ;
! echo started loading into scct_db.so_line_kpi;
! echo completed so_line_kpi data load;
---jobname:scct-usposo-hive-stg1-so_line_kpi_dcoutboundso -------------------------------------------------------------------------- ---target: stage1 table: scct_db.so_line_kpi  ---source: tms_stage0 table : delivery_master, handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 07jan20 scctp4-2924 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter --------------------------------------------------------------------------  ------------------------- ---job related hive settings  -------------------------   set hive.auto.convert.join.noconditionaltask.size=200000000;
------------------------- ---loading dd line kpi's data into so_line_kpi table -------------------------  set tez.job.name=load dd line kpis:so_line_kpi :load target from delivery_master ;
! echo started loading into scct_db.so_line_kpi;
! echo completed so_line_kpi data load;
---jobname:scct-ufposo-hive-stg1-so_line_kpi_final -------------------------------------------------------------------------- ---target: stage1 table: scct_db.po_line_kpi  ---source: tms_stage0 table : so_line_kpi_work and so_line_kpi_work1 ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 04may20 scctp4-2922 ssoma initial version ---------------------------------------------------------------------------  ------------------------- ---job related hive settings  -------------------------  set mapreduce.job.reduces=200;
------------------------- ---loading po line kpi's data into dd_line_kpi table -------------------------  set tez.job.name=load po line kpis:so_line_kpi:load target from po_master ;
! echo started loading scct_work_db.so_line_kpi_work1 for all the modules;
! echo started loading scct_work_db.so_line_kpi_work for all the modules;
! echo completed so_line_kpi data load;
---jobname:scct-ufposo-hive-stg1-so_line_kpi_vss_to_vsd -------------------------------------------------------------------------- ---target: stage1 table: scct_db.so_line_kpi  ---source: tms_stage0 table : delivery_master, handling_master and item_unit_measure_master ---load type: full ---back posting: no -- -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ -------------------- -- 01.00.00.01 07jan20 scctp4-2924 ssoma initial version -- 01.00.00.02 06mar20 scctp4-3316 ssoma remove reducer parameter -- 01.00.00.03 04may20 scctp4-3331 ssoma hql optimization  --------------------------------------------------------------------------  ------------------------- ---job related hive settings  -------------------------    set hive.auto.convert.join.noconditionaltask.size=200000000;
------------------------- ---loading dd line kpi's data into so_line_kpi table -------------------------  set tez.job.name=load dd line kpis:so_line_kpi :load target from delivery_master ;
! echo started loading into scct_db.so_line_kpi;
! echo completed so_line_kpi data load;
---jobname:scct-masterdata-hive-stg1-scct_db.so_master -------------------------------------------------------------------------- ---target: stage1 table: so_master ---source: scct_raw_db.maprdb_vbak_raw, scct_raw_db.vbpa_raw, scct_raw_db.maprdb_vbap_raw ---load type: delta ---back posting: no -------------------------------------------------------------------------  -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ ---------------------------- -- 01.00.00.01 23may19 ssoma initial version -- 01.00.00.02 23sep19 scctp4-2471 ryadav mapr remediation changes for column names, item and location length -- 01.00.00.03 26sep19 scctp4-2481 ryadav added lpad in location join -- 01.00.00.04 04nov19 scctp4-2638 ssoma added cust_prch_itm_nbr(posex) column into so_master -- 01.00.00.05 03jun20 scctp4-1777 ashettap added chngind column into so_master -- 01.00.00.06 03jul20 scctp5-217 ashettap added 9 columns from sls_distr_doc_nbr through overall_sls_ord_blk_stat to so_master  ------------------------- ---job related hive settings to read huge dataset and merge files for target table -------------------------  set hive.auto.convert.join.noconditionaltask.size=3000000000;
------------------------- ---loading so_master stage 1 base table -------------------------  set tez.job.name=stage1:load_so_master:load_so_master;
! echo started loading into scct_db.so_master;
INSERT OVERWRITE INTO SCCT_DB.SO_MASTER
(SELECT SLS_ORD_NBR, SLS_ORD_ITM_NBR, ITM_NBR, DELIV_ITM_CAT, REJ_RSN, PROD_HIER, DOC_CURRCY_VAL, TGT_SLS_UNT_QTY, TGT_QTY_UOM, CONVN_FCT_1, CONVN_FCT_2, BASE_UOM, NET_VAL, CURRCY, ORD_QTY_SLS_UNT, REQ_DELIV_QTY_SLS_UNT, CONFRMD_QTY_SLS_UNT, CONFRMD_QTY_BASE_UNT, SLS_UNT, NUM_CONVN, DENOM_CONVN, GRS_WGT, NET_WGT, WGT_UNT, VOL, VOL_UNT, ORIGTG_DOC, ORIGTG_ITM, REF_ITM_NBR, DELIV_PRTY, COALESCE(RCVL.LOCATION_NUMBER, TMP.RECV_LOC_NBR), COALESCE(SRL.LOCATION_NUMBER, TMP.SHIP_RECV_LOC_NBR), REC_CRTD_DT, REC_CRTD_ID, REC_ENTR_TM, NET_PRC, COND_PRC_UNT, COND_UOM, COST, PRC_COND_SUBT_1, PRC_COND_SUBT_2, PRC_COND_SUBT_3, PRC_COND_SUBT_4, PRC_COND_SUBT_5, PRC_COND_SUBT_6, EXCHG_RT_STATS, REC_CHGD_DT, PCTR, SPEC_STK_IND, PRFT_SEG, CONVN_FCT, REQMS_TYPE, ITM_CR_PRC, ACTV_CR_FUNC, CR_EXCHG_RT, CNFGRN_INTRNL_OBJ_NBR, CUST_CLS, CUST_STYLE, STYLE_DESC, ORIG_QTY, ORIG_UOM, ORIG_ITM_PRC, ORIG_CUST_ITM_PRC, REV_CUST_ITM_PRC, CNCL_DT, DN_SHP_DT, CUST_DEPT_CD, DOC_DT, SLS_DOC_CAT, TRANS_GRP, SLS_DOC_TYPE, ORD_RSN, SLS_DOC_CRCY, SLS_ORG, DISTR_CHNL, DIVISION, SLS_GRP, SLS_OFC, NBR_DOC_COND, REQSTD_DT, PRPSD_DT_TYPE, PROC, SHP_COND, SLS_PROB, CUST_PRCH_NBR, CUST_ORD_TYPE, CUST_PRCH_ORD_DT, NBR_CNTC_CUST, CUST_NBR, UPD_STATS_GRP, STATS_CRCY, CNTLG_AREA, CR_CNTL_AREA, CR_RSK, CR_VAL_CRCY, RLSED_CR_VAL_DOC, HIER_TYPE_PRC, CO_CD_BILLD, REF_DOC_NBR, ARTCL_AVAIL_DT, GUID_KEY, TOT_ORD_QTY, ORIG_TOT_PRC, REV_TOT_PRC, CPO_STAT, CPO_TYPE, MAST_NBR, PRE_TICKT, MEDIA_CD, COALESCE(SHPL.LOCATION_NUMBER, TMP.SHIP_TO_LOC_NBR), CNTRY_CD, SHP_TO_DESC, PARTN_FUNC, RNDG_QTY, PURCH_ORD_ITM_NBR, DELV_GRP, QTY_FIXD, UNLTD_OD, OD_TOLNC, UND_DELV_TOLNC, BTCH_SPLT_ALWD, REF_DOC_NBR_DTL, COMPL_REF, ROUTE, INTNL_PROD_NBR, CMPNT_QLTY, CUST_LNG_SKU, MAST_STYLE_NBR, CUST_COLOR_CD, CUST_COLOR_DESC, CUST_SZ_CD, CO_SZ_DESC, PRE_PACK_MSTR_SKU, PRE_PACK_SORT_CD, ORIG_NDC_DT, DN_SHP_ERLR_DT, CUST_GARMENT_CLS, VEND_STYLE_CD, PRE_PACK_CD, PACK_TYPE, GAC_DT, PACK_CNT, CORSP_ARTCL_NBR_SHRD, REC_CRTD_DT_HDR, REC_CRTD_ID_HDR, DELV_BLK, BLLG_BLK, REC_CHGD_DT_HDR, REF_DOC_NBR_HDR, CNTNS_DG, COORIG_CD, CUST_PRCH_ITM_NBR, DEL_IND, SLS_ORD_ITM_DELV_DT, SLS_ORD_ITM_REQ_DT, SLS_ORD_ITM_RSRVN_DT, SLS_ORD_ITM_PKG_RTRN_DT, SLS_ORD_ITM_TRANSP_PLNG_DT, SLS_ORD_ITM_MTRL_STNG_DT, SLS_ORD_ITM_LOADG_DT, SLS_ORD_ITM_GDS_ISS_DT, SLS_ORD_ITM_ARRIV_TM, SLS_ORD_ITM_DT_TYP, SLS_DISTR_DOC_NBR, SLS_ORD_DEL_STAT, OVERALL_SLS_ORD_DEL_STAT_ALL_ITM, OVERALL_REJCT_STAT_ALL_SLS_DOC_ITM, OVERALL_DOC_PRCSSG_STAT, OVERALL_CR_CK_STAT, OVERALL_BILLG_BLK_STAT, OVERALL_SLS_ORD_DEL_BLK_STAT, OVERALL_SLS_ORD_BLK_STAT
FROM SCCT_WORK_DB.SO_MASTER_TMP AS TMP
LEFT JOIN (SELECT LOCATION_NUMBER
FROM ANALYTICS_DB.LOCATION
WHERE LOCATION_TYPE_CODE = '04') AS SHPL ON LPAD(TMP.SHIP_TO_LOC_NBR, 10, 0) = SHPL.LOCATION_NUMBER
LEFT JOIN (SELECT LOCATION_NUMBER
FROM ANALYTICS_DB.LOCATION
WHERE LOCATION_TYPE_CODE = '04') AS RCVL ON LPAD(TMP.RECV_LOC_NBR, 10, 0) = RCVL.LOCATION_NUMBER
LEFT JOIN (SELECT LOCATION_NUMBER
FROM ANALYTICS_DB.LOCATION
WHERE LOCATION_TYPE_CODE = '04') AS SRL ON LPAD(TMP.SHIP_RECV_LOC_NBR, 10, 0) = SRL.LOCATION_NUMBER);
