SELECT ISS.I_BRAND_ID AS BRAND_ID, ISS.I_CLASS_ID AS CLASS_ID, ISS.I_CATEGORY_ID AS CATEGORY_ID
FROM TPCDS_BIN_PARTITIONED_ORC_5.STORE_SALES,
TPCDS_BIN_PARTITIONED_ORC_5.ITEM AS ISS,
TPCDS_BIN_PARTITIONED_ORC_5.DATE_DIM AS D1
WHERE SS_ITEM_SK = ISS.I_ITEM_SK AND SS_SOLD_DATE_SK = D1.D_DATE_SK AND D1.D_YEAR BETWEEN ASYMMETRIC 1999 AND 1999 + 2
UNION
SELECT ICS.I_BRAND_ID, ICS.I_CLASS_ID, ICS.I_CATEGORY_ID
FROM TPCDS_BIN_PARTITIONED_ORC_5.CATALOG_SALES,
TPCDS_BIN_PARTITIONED_ORC_5.ITEM AS ICS,
TPCDS_BIN_PARTITIONED_ORC_5.DATE_DIM AS D2
WHERE CS_ITEM_SK = ICS.I_ITEM_SK AND CS_SOLD_DATE_SK = D2.D_DATE_SK AND D2.D_YEAR BETWEEN ASYMMETRIC 1999 AND 1999 + 2
UNION
SELECT IWS.I_BRAND_ID, IWS.I_CLASS_ID, IWS.I_CATEGORY_ID
FROM TPCDS_BIN_PARTITIONED_ORC_5.WEB_SALES,
TPCDS_BIN_PARTITIONED_ORC_5.ITEM AS IWS,
TPCDS_BIN_PARTITIONED_ORC_5.DATE_DIM AS D3
WHERE WS_ITEM_SK = IWS.I_ITEM_SK AND WS_SOLD_DATE_SK = D3.D_DATE_SK AND D3.D_YEAR BETWEEN ASYMMETRIC 1999 AND 1999 + 2
SELECT ISS.I_BRAND_ID AS BRAND_ID, ISS.I_CLASS_ID AS CLASS_ID, ISS.I_CATEGORY_ID AS CATEGORY_ID
FROM TPCDS_BIN_PARTITIONED_ORC_5.STORE_SALES,
TPCDS_BIN_PARTITIONED_ORC_5.ITEM AS ISS,
TPCDS_BIN_PARTITIONED_ORC_5.DATE_DIM AS D1
WHERE SS_ITEM_SK = ISS.I_ITEM_SK AND SS_SOLD_DATE_SK = D1.D_DATE_SK AND D1.D_YEAR BETWEEN ASYMMETRIC 1999 AND 1999 + 2
UNION
SELECT ICS.I_BRAND_ID, ICS.I_CLASS_ID, ICS.I_CATEGORY_ID
FROM TPCDS_BIN_PARTITIONED_ORC_5.CATALOG_SALES,
TPCDS_BIN_PARTITIONED_ORC_5.ITEM AS ICS,
TPCDS_BIN_PARTITIONED_ORC_5.DATE_DIM AS D2
WHERE CS_ITEM_SK = ICS.I_ITEM_SK AND CS_SOLD_DATE_SK = D2.D_DATE_SK AND D2.D_YEAR BETWEEN ASYMMETRIC 1999 AND 1999 + 2
UNION
SELECT IWS.I_BRAND_ID, IWS.I_CLASS_ID, IWS.I_CATEGORY_ID
FROM TPCDS_BIN_PARTITIONED_ORC_5.WEB_SALES,
TPCDS_BIN_PARTITIONED_ORC_5.ITEM AS IWS,
TPCDS_BIN_PARTITIONED_ORC_5.DATE_DIM AS D3
WHERE WS_ITEM_SK = IWS.I_ITEM_SK AND WS_SOLD_DATE_SK = D3.D_DATE_SK AND D3.D_YEAR BETWEEN ASYMMETRIC 1999 AND 1999 + 2
SELECT ISS.I_BRAND_ID AS BRAND_ID, ISS.I_CLASS_ID AS CLASS_ID, ISS.I_CATEGORY_ID AS CATEGORY_ID
FROM TPCDS_BIN_PARTITIONED_ORC_5.STORE_SALES,
TPCDS_BIN_PARTITIONED_ORC_5.ITEM AS ISS,
TPCDS_BIN_PARTITIONED_ORC_5.DATE_DIM AS D1
WHERE SS_ITEM_SK = ISS.I_ITEM_SK AND SS_SOLD_DATE_SK = D1.D_DATE_SK AND D1.D_YEAR BETWEEN ASYMMETRIC 1999 AND 1999 + 2
UNION
SELECT ICS.I_BRAND_ID, ICS.I_CLASS_ID, ICS.I_CATEGORY_ID
FROM TPCDS_BIN_PARTITIONED_ORC_5.CATALOG_SALES,
TPCDS_BIN_PARTITIONED_ORC_5.ITEM AS ICS,
TPCDS_BIN_PARTITIONED_ORC_5.DATE_DIM AS D2
WHERE CS_ITEM_SK = ICS.I_ITEM_SK AND CS_SOLD_DATE_SK = D2.D_DATE_SK AND D2.D_YEAR BETWEEN ASYMMETRIC 1999 AND 1999 + 2
UNION
SELECT IWS.I_BRAND_ID, IWS.I_CLASS_ID, IWS.I_CATEGORY_ID
FROM TPCDS_BIN_PARTITIONED_ORC_5.WEB_SALES,
TPCDS_BIN_PARTITIONED_ORC_5.ITEM AS IWS,
TPCDS_BIN_PARTITIONED_ORC_5.DATE_DIM AS D3
WHERE WS_ITEM_SK = IWS.I_ITEM_SK AND WS_SOLD_DATE_SK = D3.D_DATE_SK AND D3.D_YEAR BETWEEN ASYMMETRIC 1999 AND 1999 + 2
