WITH SSR AS (SELECT S_STORE_ID, SUM(SALES_PRICE) AS SALES, SUM(PROFIT) AS PROFIT, SUM(RETURN_AMT) AS RETURNS, SUM(NET_LOSS) AS PROFIT_LOSS
FROM (SELECT SS_STORE_SK AS STORE_SK, SS_SOLD_DATE_SK AS DATE_SK, SS_EXT_SALES_PRICE AS SALES_PRICE, SS_NET_PROFIT AS PROFIT, CAST(0 AS DECIMAL(7, 2)) AS RETURN_AMT, CAST(0 AS DECIMAL(7, 2)) AS NET_LOSS
FROM STORE_SALES
UNION
SELECT SR_STORE_SK AS STORE_SK, SR_RETURNED_DATE_SK AS DATE_SK, CAST(0 AS DECIMAL(7, 2)) AS SALES_PRICE, CAST(0 AS DECIMAL(7, 2)) AS PROFIT, SR_RETURN_AMT AS RETURN_AMT, SR_NET_LOSS AS NET_LOSS
FROM STORE_RETURNS) AS SALESRETURNS,
DATE_DIM,
STORE
WHERE DATE_SK = D_DATE_SK AND D_DATE BETWEEN ASYMMETRIC CAST('2000-08-23', DATE) AND DATE_ADD(CAST('2000-05-24' AS DATE), CAST('12.34' AS int)) AND STORE_SK = S_STORE_SK
GROUP BY S_STORE_ID), CSR AS (SELECT CP_CATALOG_PAGE_ID, SUM(SALES_PRICE) AS SALES, SUM(PROFIT) AS PROFIT, SUM(RETURN_AMT) AS RETURNS, SUM(NET_LOSS) AS PROFIT_LOSS
FROM (SELECT CS_CATALOG_PAGE_SK AS PAGE_SK, CS_SOLD_DATE_SK AS DATE_SK, CS_EXT_SALES_PRICE AS SALES_PRICE, CS_NET_PROFIT AS PROFIT, CAST(0 AS DECIMAL(7, 2)) AS RETURN_AMT, CAST(0 AS DECIMAL(7, 2)) AS NET_LOSS
FROM CATALOG_SALES
UNION
SELECT CR_CATALOG_PAGE_SK AS PAGE_SK, CR_RETURNED_DATE_SK AS DATE_SK, CAST(0 AS DECIMAL(7, 2)) AS SALES_PRICE, CAST(0 AS DECIMAL(7, 2)) AS PROFIT, CR_RETURN_AMOUNT AS RETURN_AMT, CR_NET_LOSS AS NET_LOSS
FROM CATALOG_RETURNS) AS SALESRETURNS,
DATE_DIM,
CATALOG_PAGE
WHERE DATE_SK = D_DATE_SK AND D_DATE BETWEEN ASYMMETRIC CAST('2000-08-23', DATE) AND DATE_ADD(CAST('2000-05-24' AS DATE), CAST('12.34' AS int)) AND PAGE_SK = CP_CATALOG_PAGE_SK
GROUP BY CP_CATALOG_PAGE_ID), WSR AS (SELECT WEB_SITE_ID, SUM(SALES_PRICE) AS SALES, SUM(PROFIT) AS PROFIT, SUM(RETURN_AMT) AS RETURNS, SUM(NET_LOSS) AS PROFIT_LOSS
FROM (SELECT WS_WEB_SITE_SK AS WSR_WEB_SITE_SK, WS_SOLD_DATE_SK AS DATE_SK, WS_EXT_SALES_PRICE AS SALES_PRICE, WS_NET_PROFIT AS PROFIT, CAST(0 AS DECIMAL(7, 2)) AS RETURN_AMT, CAST(0 AS DECIMAL(7, 2)) AS NET_LOSS
FROM WEB_SALES
UNION
SELECT WS_WEB_SITE_SK AS WSR_WEB_SITE_SK, WR_RETURNED_DATE_SK AS DATE_SK, CAST(0 AS DECIMAL(7, 2)) AS SALES_PRICE, CAST(0 AS DECIMAL(7, 2)) AS PROFIT, WR_RETURN_AMT AS RETURN_AMT, WR_NET_LOSS AS NET_LOSS
FROM WEB_RETURNS
LEFT JOIN WEB_SALES ON WR_ITEM_SK = WS_ITEM_SK AND WR_ORDER_NUMBER = WS_ORDER_NUMBER) AS SALESRETURNS,
DATE_DIM,
WEB_SITE
WHERE DATE_SK = D_DATE_SK AND D_DATE BETWEEN ASYMMETRIC CAST('2000-08-23', DATE) AND CAST('2000-08-23', DATE) AND WSR_WEB_SITE_SK = WEB_SITE_SK
GROUP BY WEB_SITE_ID) (SELECT CHANNEL, ID, SUM(SALES) AS SALES, SUM(RETURNS) AS RETURNS, SUM(PROFIT) AS PROFIT
FROM (SELECT 'store channel' AS CHANNEL, CONCAT('store', S_STORE_ID) AS ID, SALES, RETURNS, PROFIT - PROFIT_LOSS AS PROFIT
FROM SSR
UNION
SELECT 'catalog channel' AS CHANNEL, CONCAT('catalog_page', CP_CATALOG_PAGE_ID) AS ID, SALES, RETURNS, PROFIT - PROFIT_LOSS AS PROFIT
FROM CSR
UNION
SELECT 'web channel' AS CHANNEL, CONCAT('web_site', WEB_SITE_ID) AS ID, SALES, RETURNS, PROFIT - PROFIT_LOSS AS PROFIT
FROM WSR) AS X
GROUP BY ROLLUP(CHANNEL, ID))
ORDER BY CHANNEL, ID
FETCH NEXT 100 ROWS ONLY
WITH SSR AS (SELECT S_STORE_ID, SUM(SALES_PRICE) AS SALES, SUM(PROFIT) AS PROFIT, SUM(RETURN_AMT) AS RETURNS, SUM(NET_LOSS) AS PROFIT_LOSS
FROM (SELECT SS_STORE_SK AS STORE_SK, SS_SOLD_DATE_SK AS DATE_SK, SS_EXT_SALES_PRICE AS SALES_PRICE, SS_NET_PROFIT AS PROFIT, CAST(0 AS DECIMAL(7, 2)) AS RETURN_AMT, CAST(0 AS DECIMAL(7, 2)) AS NET_LOSS
FROM STORE_SALES
UNION
SELECT SR_STORE_SK AS STORE_SK, SR_RETURNED_DATE_SK AS DATE_SK, CAST(0 AS DECIMAL(7, 2)) AS SALES_PRICE, CAST(0 AS DECIMAL(7, 2)) AS PROFIT, SR_RETURN_AMT AS RETURN_AMT, SR_NET_LOSS AS NET_LOSS
FROM STORE_RETURNS) AS SALESRETURNS,
DATE_DIM,
STORE
WHERE DATE_SK = D_DATE_SK AND D_DATE BETWEEN ASYMMETRIC CAST('2000-08-23', DATE) AND DATE_ADD(CAST('2000-05-24' AS DATE), CAST('12.34' AS int)) AND STORE_SK = S_STORE_SK
GROUP BY S_STORE_ID), CSR AS (SELECT CP_CATALOG_PAGE_ID, SUM(SALES_PRICE) AS SALES, SUM(PROFIT) AS PROFIT, SUM(RETURN_AMT) AS RETURNS, SUM(NET_LOSS) AS PROFIT_LOSS
FROM (SELECT CS_CATALOG_PAGE_SK AS PAGE_SK, CS_SOLD_DATE_SK AS DATE_SK, CS_EXT_SALES_PRICE AS SALES_PRICE, CS_NET_PROFIT AS PROFIT, CAST(0 AS DECIMAL(7, 2)) AS RETURN_AMT, CAST(0 AS DECIMAL(7, 2)) AS NET_LOSS
FROM CATALOG_SALES
UNION
SELECT CR_CATALOG_PAGE_SK AS PAGE_SK, CR_RETURNED_DATE_SK AS DATE_SK, CAST(0 AS DECIMAL(7, 2)) AS SALES_PRICE, CAST(0 AS DECIMAL(7, 2)) AS PROFIT, CR_RETURN_AMOUNT AS RETURN_AMT, CR_NET_LOSS AS NET_LOSS
FROM CATALOG_RETURNS) AS SALESRETURNS,
DATE_DIM,
CATALOG_PAGE
WHERE DATE_SK = D_DATE_SK AND D_DATE BETWEEN ASYMMETRIC CAST('2000-08-23', DATE) AND DATE_ADD(CAST('2000-05-24' AS DATE), CAST('12.34' AS int)) AND PAGE_SK = CP_CATALOG_PAGE_SK
GROUP BY CP_CATALOG_PAGE_ID), WSR AS (SELECT WEB_SITE_ID, SUM(SALES_PRICE) AS SALES, SUM(PROFIT) AS PROFIT, SUM(RETURN_AMT) AS RETURNS, SUM(NET_LOSS) AS PROFIT_LOSS
FROM (SELECT WS_WEB_SITE_SK AS WSR_WEB_SITE_SK, WS_SOLD_DATE_SK AS DATE_SK, WS_EXT_SALES_PRICE AS SALES_PRICE, WS_NET_PROFIT AS PROFIT, CAST(0 AS DECIMAL(7, 2)) AS RETURN_AMT, CAST(0 AS DECIMAL(7, 2)) AS NET_LOSS
FROM WEB_SALES
UNION
SELECT WS_WEB_SITE_SK AS WSR_WEB_SITE_SK, WR_RETURNED_DATE_SK AS DATE_SK, CAST(0 AS DECIMAL(7, 2)) AS SALES_PRICE, CAST(0 AS DECIMAL(7, 2)) AS PROFIT, WR_RETURN_AMT AS RETURN_AMT, WR_NET_LOSS AS NET_LOSS
FROM WEB_RETURNS
LEFT JOIN WEB_SALES ON WR_ITEM_SK = WS_ITEM_SK AND WR_ORDER_NUMBER = WS_ORDER_NUMBER) AS SALESRETURNS,
DATE_DIM,
WEB_SITE
WHERE DATE_SK = D_DATE_SK AND D_DATE BETWEEN ASYMMETRIC CAST('2000-08-23', DATE) AND CAST('2000-08-23', DATE) AND WSR_WEB_SITE_SK = WEB_SITE_SK
GROUP BY WEB_SITE_ID) (SELECT CHANNEL, ID, SUM(SALES) AS SALES, SUM(RETURNS) AS RETURNS, SUM(PROFIT) AS PROFIT
FROM (SELECT 'store channel' AS CHANNEL, CONCAT('store', S_STORE_ID) AS ID, SALES, RETURNS, PROFIT - PROFIT_LOSS AS PROFIT
FROM SSR
UNION
SELECT 'catalog channel' AS CHANNEL, CONCAT('catalog_page', CP_CATALOG_PAGE_ID) AS ID, SALES, RETURNS, PROFIT - PROFIT_LOSS AS PROFIT
FROM CSR
UNION
SELECT 'web channel' AS CHANNEL, CONCAT('web_site', WEB_SITE_ID) AS ID, SALES, RETURNS, PROFIT - PROFIT_LOSS AS PROFIT
FROM WSR) AS X
GROUP BY ROLLUP(CHANNEL, ID))
ORDER BY CHANNEL, ID
FETCH NEXT 100 ROWS ONLY
WITH SSR AS (SELECT S_STORE_ID, SUM(SALES_PRICE) AS SALES, SUM(PROFIT) AS PROFIT, SUM(RETURN_AMT) AS RETURNS, SUM(NET_LOSS) AS PROFIT_LOSS
FROM (SELECT SS_STORE_SK AS STORE_SK, SS_SOLD_DATE_SK AS DATE_SK, SS_EXT_SALES_PRICE AS SALES_PRICE, SS_NET_PROFIT AS PROFIT, CAST(0 AS DECIMAL(7, 2)) AS RETURN_AMT, CAST(0 AS DECIMAL(7, 2)) AS NET_LOSS
FROM STORE_SALES
UNION
SELECT SR_STORE_SK AS STORE_SK, SR_RETURNED_DATE_SK AS DATE_SK, CAST(0 AS DECIMAL(7, 2)) AS SALES_PRICE, CAST(0 AS DECIMAL(7, 2)) AS PROFIT, SR_RETURN_AMT AS RETURN_AMT, SR_NET_LOSS AS NET_LOSS
FROM STORE_RETURNS) AS SALESRETURNS,
DATE_DIM,
STORE
WHERE DATE_SK = D_DATE_SK AND D_DATE BETWEEN ASYMMETRIC CAST('2000-08-23', DATE) AND DATE_ADD(CAST('2000-05-24' AS DATE), CAST('12.34' AS int)) AND STORE_SK = S_STORE_SK
GROUP BY S_STORE_ID), CSR AS (SELECT CP_CATALOG_PAGE_ID, SUM(SALES_PRICE) AS SALES, SUM(PROFIT) AS PROFIT, SUM(RETURN_AMT) AS RETURNS, SUM(NET_LOSS) AS PROFIT_LOSS
FROM (SELECT CS_CATALOG_PAGE_SK AS PAGE_SK, CS_SOLD_DATE_SK AS DATE_SK, CS_EXT_SALES_PRICE AS SALES_PRICE, CS_NET_PROFIT AS PROFIT, CAST(0 AS DECIMAL(7, 2)) AS RETURN_AMT, CAST(0 AS DECIMAL(7, 2)) AS NET_LOSS
FROM CATALOG_SALES
UNION
SELECT CR_CATALOG_PAGE_SK AS PAGE_SK, CR_RETURNED_DATE_SK AS DATE_SK, CAST(0 AS DECIMAL(7, 2)) AS SALES_PRICE, CAST(0 AS DECIMAL(7, 2)) AS PROFIT, CR_RETURN_AMOUNT AS RETURN_AMT, CR_NET_LOSS AS NET_LOSS
FROM CATALOG_RETURNS) AS SALESRETURNS,
DATE_DIM,
CATALOG_PAGE
WHERE DATE_SK = D_DATE_SK AND D_DATE BETWEEN ASYMMETRIC CAST('2000-08-23', DATE) AND DATE_ADD(CAST('2000-05-24' AS DATE), CAST('12.34' AS int)) AND PAGE_SK = CP_CATALOG_PAGE_SK
GROUP BY CP_CATALOG_PAGE_ID), WSR AS (SELECT WEB_SITE_ID, SUM(SALES_PRICE) AS SALES, SUM(PROFIT) AS PROFIT, SUM(RETURN_AMT) AS RETURNS, SUM(NET_LOSS) AS PROFIT_LOSS
FROM (SELECT WS_WEB_SITE_SK AS WSR_WEB_SITE_SK, WS_SOLD_DATE_SK AS DATE_SK, WS_EXT_SALES_PRICE AS SALES_PRICE, WS_NET_PROFIT AS PROFIT, CAST(0 AS DECIMAL(7, 2)) AS RETURN_AMT, CAST(0 AS DECIMAL(7, 2)) AS NET_LOSS
FROM WEB_SALES
UNION
SELECT WS_WEB_SITE_SK AS WSR_WEB_SITE_SK, WR_RETURNED_DATE_SK AS DATE_SK, CAST(0 AS DECIMAL(7, 2)) AS SALES_PRICE, CAST(0 AS DECIMAL(7, 2)) AS PROFIT, WR_RETURN_AMT AS RETURN_AMT, WR_NET_LOSS AS NET_LOSS
FROM WEB_RETURNS
LEFT JOIN WEB_SALES ON WR_ITEM_SK = WS_ITEM_SK AND WR_ORDER_NUMBER = WS_ORDER_NUMBER) AS SALESRETURNS,
DATE_DIM,
WEB_SITE
WHERE DATE_SK = D_DATE_SK AND D_DATE BETWEEN ASYMMETRIC CAST('2000-08-23', DATE) AND CAST('2000-08-23', DATE) AND WSR_WEB_SITE_SK = WEB_SITE_SK
GROUP BY WEB_SITE_ID) (SELECT CHANNEL, ID, SUM(SALES) AS SALES, SUM(RETURNS) AS RETURNS, SUM(PROFIT) AS PROFIT
FROM (SELECT 'store channel' AS CHANNEL, CONCAT('store', S_STORE_ID) AS ID, SALES, RETURNS, PROFIT - PROFIT_LOSS AS PROFIT
FROM SSR
UNION
SELECT 'catalog channel' AS CHANNEL, CONCAT('catalog_page', CP_CATALOG_PAGE_ID) AS ID, SALES, RETURNS, PROFIT - PROFIT_LOSS AS PROFIT
FROM CSR
UNION
SELECT 'web channel' AS CHANNEL, CONCAT('web_site', WEB_SITE_ID) AS ID, SALES, RETURNS, PROFIT - PROFIT_LOSS AS PROFIT
FROM WSR) AS X
GROUP BY ROLLUP(CHANNEL, ID))
ORDER BY CHANNEL, ID
FETCH NEXT 100 ROWS ONLY
