! echo completed loading into scct_db.scem_expected_events;
---jobname:scct-scem-hive-stg1-scct_db.scem_tracking_events -------------------------------------------------------------------------- ---target: stage1 table: scct_db.scem_tracking_events  ---source: sap_stage0 table : scem_tracking_events_tmp ---description: this script will load the delta data to target table scct_db.scem_tracking_events ---load type: full ---back posting: no --------------------------------------------------------------------------  -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ ---------------------------- -- 01.00.00.01 23jul19 sdhal initial version -- 01.00.00.02 06sep19 scctp4-2187 akoti changed patition key to eh_created_date and added logic to ignore records where di_operation_type <> 'd' -- 01.00.00.03 29nov19 scctp4-2623 akoti removed partition column & settings, changed di_operation_type logic --  ------------------------- ---job related hive settings to merge files for target table ------------------------- set hive.merge.orcfile.stripe.level=false;
------------------------- ---loading scem_tracking_events target table data -------------------------  set tez.job.name=stage2:scem_tracking_events :load target table scem_tracking_events ;
! echo started loading into scct_db.scem_tracking_events ;
insert overwrite table `scct_db.scem_tracking_events` select  eh_guid , bw_profile , event_code , evt_msg_guid , servprov_cd , loc_cd_1 , info_type , eh_type , servprov_cs , loc_cs , loc_cd_2 , event_group , event_status , msg_status , rsn_cs_status , rsn_cd_status , sender_cs , sender_cd , recipient_cs , recipient_cd , msg_srctype , msg_utc_date , msg_utc_time , msg_exp_tzone , msg_exp_date , msg_exp_time , msg_org_exp_date , msg_org_exp_time , msg_ear_exp_date , msg_ear_exp_time , msg_lat_exp_date , msg_lat_exp_time , evt_utc_date , evt_utc_time , evt_est_date , evt_est_time , evt_est_date_time , evt_exp_tzone , evt_exp_date , evt_exp_time , evt_org_exp_date , evt_org_exp_time , evt_ear_exp_date , evt_ear_exp_time , evt_lat_exp_date , evt_lat_exp_time , evt_ao_exp_date , evt_ao_exp_time , evt_duration_01 , evt_duration_02 , evt_duration_03 , evt_duration_04 , evt_duration_05 , msg_exp_duration , evt_exp_duration , planned_tot_dur , planned_eff_dur , evt_msg_cntr , em_client , rocancel , date1 , time1 , tzone1 , date2 , time2 , tzone2 , date3 , time3 , tzone3 , date4 , time4 , tzone4 , date5 , time5 , tzone5 , datacs , dataid , carrarrival_date , carrarrival_time , hubarrival_date , hubarrival_time , hubdepart_date , hubdepart_time , srctx , event_reasontext , event_sendername , username from  scct_work_db.scem_tracking_events_tmp where upper(di_operation_type) in ('i','u','e')
! echo completed loading into scct_db.scem_tracking_events ;
! echo completed loading into scct_db.scem_expected_events;
---jobname:scct-scem-hive-stg1-scct_db.scem_tracking_events -------------------------------------------------------------------------- ---target: stage1 table: scct_db.scem_tracking_events  ---source: sap_stage0 table : scem_tracking_events_tmp ---description: this script will load the delta data to target table scct_db.scem_tracking_events ---load type: full ---back posting: no --------------------------------------------------------------------------  -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ ---------------------------- -- 01.00.00.01 23jul19 sdhal initial version -- 01.00.00.02 06sep19 scctp4-2187 akoti changed patition key to eh_created_date and added logic to ignore records where di_operation_type <> 'd' -- 01.00.00.03 29nov19 scctp4-2623 akoti removed partition column & settings, changed di_operation_type logic --  ------------------------- ---job related hive settings to merge files for target table ------------------------- set hive.merge.orcfile.stripe.level=false;
------------------------- ---loading scem_tracking_events target table data -------------------------  set tez.job.name=stage2:scem_tracking_events :load target table scem_tracking_events ;
! echo started loading into scct_db.scem_tracking_events ;
insert overwrite table `scct_db.scem_tracking_events` select  eh_guid , bw_profile , event_code , evt_msg_guid , servprov_cd , loc_cd_1 , info_type , eh_type , servprov_cs , loc_cs , loc_cd_2 , event_group , event_status , msg_status , rsn_cs_status , rsn_cd_status , sender_cs , sender_cd , recipient_cs , recipient_cd , msg_srctype , msg_utc_date , msg_utc_time , msg_exp_tzone , msg_exp_date , msg_exp_time , msg_org_exp_date , msg_org_exp_time , msg_ear_exp_date , msg_ear_exp_time , msg_lat_exp_date , msg_lat_exp_time , evt_utc_date , evt_utc_time , evt_est_date , evt_est_time , evt_est_date_time , evt_exp_tzone , evt_exp_date , evt_exp_time , evt_org_exp_date , evt_org_exp_time , evt_ear_exp_date , evt_ear_exp_time , evt_lat_exp_date , evt_lat_exp_time , evt_ao_exp_date , evt_ao_exp_time , evt_duration_01 , evt_duration_02 , evt_duration_03 , evt_duration_04 , evt_duration_05 , msg_exp_duration , evt_exp_duration , planned_tot_dur , planned_eff_dur , evt_msg_cntr , em_client , rocancel , date1 , time1 , tzone1 , date2 , time2 , tzone2 , date3 , time3 , tzone3 , date4 , time4 , tzone4 , date5 , time5 , tzone5 , datacs , dataid , carrarrival_date , carrarrival_time , hubarrival_date , hubarrival_time , hubdepart_date , hubdepart_time , srctx , event_reasontext , event_sendername , username from  scct_work_db.scem_tracking_events_tmp where upper(di_operation_type) in ('i','u','e')
! echo completed loading into scct_db.scem_tracking_events ;
! echo completed loading into scct_db.scem_expected_events;
---jobname:scct-scem-hive-stg1-scct_db.scem_tracking_events -------------------------------------------------------------------------- ---target: stage1 table: scct_db.scem_tracking_events  ---source: sap_stage0 table : scem_tracking_events_tmp ---description: this script will load the delta data to target table scct_db.scem_tracking_events ---load type: full ---back posting: no --------------------------------------------------------------------------  -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ ---------------------------- -- 01.00.00.01 23jul19 sdhal initial version -- 01.00.00.02 06sep19 scctp4-2187 akoti changed patition key to eh_created_date and added logic to ignore records where di_operation_type <> 'd' -- 01.00.00.03 29nov19 scctp4-2623 akoti removed partition column & settings, changed di_operation_type logic --  ------------------------- ---job related hive settings to merge files for target table ------------------------- set hive.merge.orcfile.stripe.level=false;
------------------------- ---loading scem_tracking_events target table data -------------------------  set tez.job.name=stage2:scem_tracking_events :load target table scem_tracking_events ;
! echo started loading into scct_db.scem_tracking_events ;
insert overwrite table `scct_db.scem_tracking_events` select  eh_guid , bw_profile , event_code , evt_msg_guid , servprov_cd , loc_cd_1 , info_type , eh_type , servprov_cs , loc_cs , loc_cd_2 , event_group , event_status , msg_status , rsn_cs_status , rsn_cd_status , sender_cs , sender_cd , recipient_cs , recipient_cd , msg_srctype , msg_utc_date , msg_utc_time , msg_exp_tzone , msg_exp_date , msg_exp_time , msg_org_exp_date , msg_org_exp_time , msg_ear_exp_date , msg_ear_exp_time , msg_lat_exp_date , msg_lat_exp_time , evt_utc_date , evt_utc_time , evt_est_date , evt_est_time , evt_est_date_time , evt_exp_tzone , evt_exp_date , evt_exp_time , evt_org_exp_date , evt_org_exp_time , evt_ear_exp_date , evt_ear_exp_time , evt_lat_exp_date , evt_lat_exp_time , evt_ao_exp_date , evt_ao_exp_time , evt_duration_01 , evt_duration_02 , evt_duration_03 , evt_duration_04 , evt_duration_05 , msg_exp_duration , evt_exp_duration , planned_tot_dur , planned_eff_dur , evt_msg_cntr , em_client , rocancel , date1 , time1 , tzone1 , date2 , time2 , tzone2 , date3 , time3 , tzone3 , date4 , time4 , tzone4 , date5 , time5 , tzone5 , datacs , dataid , carrarrival_date , carrarrival_time , hubarrival_date , hubarrival_time , hubdepart_date , hubdepart_time , srctx , event_reasontext , event_sendername , username from  scct_work_db.scem_tracking_events_tmp where upper(di_operation_type) in ('i','u','e')
! echo completed loading into scct_db.scem_tracking_events ;
! echo completed loading into scct_db.scem_expected_events;
---jobname:scct-scem-hive-stg1-scct_db.scem_tracking_events -------------------------------------------------------------------------- ---target: stage1 table: scct_db.scem_tracking_events  ---source: sap_stage0 table : scem_tracking_events_tmp ---description: this script will load the delta data to target table scct_db.scem_tracking_events ---load type: full ---back posting: no --------------------------------------------------------------------------  -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ ---------------------------- -- 01.00.00.01 23jul19 sdhal initial version -- 01.00.00.02 06sep19 scctp4-2187 akoti changed patition key to eh_created_date and added logic to ignore records where di_operation_type <> 'd' -- 01.00.00.03 29nov19 scctp4-2623 akoti removed partition column & settings, changed di_operation_type logic --  ------------------------- ---job related hive settings to merge files for target table ------------------------- set hive.merge.orcfile.stripe.level=false;
------------------------- ---loading scem_tracking_events target table data -------------------------  set tez.job.name=stage2:scem_tracking_events :load target table scem_tracking_events ;
! echo started loading into scct_db.scem_tracking_events ;
insert overwrite table `scct_db.scem_tracking_events` select  eh_guid , bw_profile , event_code , evt_msg_guid , servprov_cd , loc_cd_1 , info_type , eh_type , servprov_cs , loc_cs , loc_cd_2 , event_group , event_status , msg_status , rsn_cs_status , rsn_cd_status , sender_cs , sender_cd , recipient_cs , recipient_cd , msg_srctype , msg_utc_date , msg_utc_time , msg_exp_tzone , msg_exp_date , msg_exp_time , msg_org_exp_date , msg_org_exp_time , msg_ear_exp_date , msg_ear_exp_time , msg_lat_exp_date , msg_lat_exp_time , evt_utc_date , evt_utc_time , evt_est_date , evt_est_time , evt_est_date_time , evt_exp_tzone , evt_exp_date , evt_exp_time , evt_org_exp_date , evt_org_exp_time , evt_ear_exp_date , evt_ear_exp_time , evt_lat_exp_date , evt_lat_exp_time , evt_ao_exp_date , evt_ao_exp_time , evt_duration_01 , evt_duration_02 , evt_duration_03 , evt_duration_04 , evt_duration_05 , msg_exp_duration , evt_exp_duration , planned_tot_dur , planned_eff_dur , evt_msg_cntr , em_client , rocancel , date1 , time1 , tzone1 , date2 , time2 , tzone2 , date3 , time3 , tzone3 , date4 , time4 , tzone4 , date5 , time5 , tzone5 , datacs , dataid , carrarrival_date , carrarrival_time , hubarrival_date , hubarrival_time , hubdepart_date , hubdepart_time , srctx , event_reasontext , event_sendername , username from  scct_work_db.scem_tracking_events_tmp where upper(di_operation_type) in ('i','u','e')
! echo completed loading into scct_db.scem_tracking_events ;
! echo completed loading into scct_db.scem_expected_events;
---jobname:scct-scem-hive-stg1-scct_db.scem_tracking_events -------------------------------------------------------------------------- ---target: stage1 table: scct_db.scem_tracking_events  ---source: sap_stage0 table : scem_tracking_events_tmp ---description: this script will load the delta data to target table scct_db.scem_tracking_events ---load type: full ---back posting: no --------------------------------------------------------------------------  -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ ---------------------------- -- 01.00.00.01 23jul19 sdhal initial version -- 01.00.00.02 06sep19 scctp4-2187 akoti changed patition key to eh_created_date and added logic to ignore records where di_operation_type <> 'd' -- 01.00.00.03 29nov19 scctp4-2623 akoti removed partition column & settings, changed di_operation_type logic --  ------------------------- ---job related hive settings to merge files for target table ------------------------- set hive.merge.orcfile.stripe.level=false;
------------------------- ---loading scem_tracking_events target table data -------------------------  set tez.job.name=stage2:scem_tracking_events :load target table scem_tracking_events ;
! echo started loading into scct_db.scem_tracking_events ;
! echo completed loading into scct_db.scem_tracking_events ;
! echo completed loading into scct_db.scem_expected_events;
---jobname:scct-scem-hive-stg1-scct_db.scem_tracking_events -------------------------------------------------------------------------- ---target: stage1 table: scct_db.scem_tracking_events  ---source: sap_stage0 table : scem_tracking_events_tmp ---description: this script will load the delta data to target table scct_db.scem_tracking_events ---load type: full ---back posting: no --------------------------------------------------------------------------  -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ ---------------------------- -- 01.00.00.01 23jul19 sdhal initial version -- 01.00.00.02 06sep19 scctp4-2187 akoti changed patition key to eh_created_date and added logic to ignore records where di_operation_type <> 'd' -- 01.00.00.03 29nov19 scctp4-2623 akoti removed partition column & settings, changed di_operation_type logic --  ------------------------- ---job related hive settings to merge files for target table ------------------------- set hive.merge.orcfile.stripe.level=false;
------------------------- ---loading scem_tracking_events target table data -------------------------  set tez.job.name=stage2:scem_tracking_events :load target table scem_tracking_events ;
! echo started loading into scct_db.scem_tracking_events ;
! echo completed loading into scct_db.scem_tracking_events ;
! echo completed loading into scct_db.scem_expected_events;
---jobname:scct-scem-hive-stg1-scct_db.scem_tracking_events -------------------------------------------------------------------------- ---target: stage1 table: scct_db.scem_tracking_events  ---source: sap_stage0 table : scem_tracking_events_tmp ---description: this script will load the delta data to target table scct_db.scem_tracking_events ---load type: full ---back posting: no --------------------------------------------------------------------------  -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ ---------------------------- -- 01.00.00.01 23jul19 sdhal initial version -- 01.00.00.02 06sep19 scctp4-2187 akoti changed patition key to eh_created_date and added logic to ignore records where di_operation_type <> 'd' -- 01.00.00.03 29nov19 scctp4-2623 akoti removed partition column & settings, changed di_operation_type logic --  ------------------------- ---job related hive settings to merge files for target table ------------------------- set hive.merge.orcfile.stripe.level=false;
------------------------- ---loading scem_tracking_events target table data -------------------------  set tez.job.name=stage2:scem_tracking_events :load target table scem_tracking_events ;
! echo started loading into scct_db.scem_tracking_events ;
! echo completed loading into scct_db.scem_tracking_events ;
! echo completed loading into scct_db.scem_expected_events;
---jobname:scct-scem-hive-stg1-scct_db.scem_tracking_events -------------------------------------------------------------------------- ---target: stage1 table: scct_db.scem_tracking_events  ---source: sap_stage0 table : scem_tracking_events_tmp ---description: this script will load the delta data to target table scct_db.scem_tracking_events ---load type: full ---back posting: no --------------------------------------------------------------------------  -- history information -- -- revision date jira developer-id comments -- ----------- ------- ---------- ------------ ---------------------------- -- 01.00.00.01 23jul19 sdhal initial version -- 01.00.00.02 06sep19 scctp4-2187 akoti changed patition key to eh_created_date and added logic to ignore records where di_operation_type <> 'd' -- 01.00.00.03 29nov19 scctp4-2623 akoti removed partition column & settings, changed di_operation_type logic --  ------------------------- ---job related hive settings to merge files for target table ------------------------- set hive.merge.orcfile.stripe.level=false;
------------------------- ---loading scem_tracking_events target table data -------------------------  set tez.job.name=stage2:scem_tracking_events :load target table scem_tracking_events ;
! echo started loading into scct_db.scem_tracking_events ;
! echo completed loading into scct_db.scem_tracking_events ;
